-- GRN Parties (vendors/suppliers)
INSERT INTO public.parties (name, type, category, is_active)
VALUES
  ('A.M Batteries & Inverters Sales & Service', 'supplier', 'Purchase', true),
  ('ABP ENTER PRISE', 'supplier', 'Purchase', true),
  ('ABP ENTERPRISES', 'supplier', 'Purchase', true),
  ('ABP Enterprises', 'supplier', 'Purchase', true),
  ('AGRIOMA LIFE SCIENCE', 'supplier', 'Purchase', true),
  ('ALIVIRA ANIMAL HEALTH LTD', 'supplier', 'Purchase', true),
  ('ALLVIRA ANIMAL HEALTH LTD.', 'supplier', 'Purchase', true),
  ('AMBIKA CEMENT & STEEL TRADERS', 'supplier', 'Purchase', true),
  ('ANJANEYULU', 'supplier', 'Purchase', true),
  ('ANJANEYULU - KANKARA', 'supplier', 'Purchase', true),
  ('APC NUTRIENTS PVT LTD', 'supplier', 'Purchase', true),
  ('APC Nutrients PVT LTD', 'supplier', 'Purchase', true),
  ('APC Nutrients Pvt Ltd', 'supplier', 'Purchase', true),
  ('APC nutrients PVT LTD', 'supplier', 'Purchase', true),
  ('ASIAN POULTRY EQUIPMENTS', 'supplier', 'Purchase', true),
  ('AVITECH NUTRITION PVT LTD', 'supplier', 'Purchase', true),
  ('Aadithya  Pulp N Pack', 'supplier', 'Purchase', true),
  ('Aadithya Packagings', 'supplier', 'Purchase', true),
  ('Aadithya Pulp N Packs', 'supplier', 'Purchase', true),
  ('Aaditya Pulp N Packs', 'supplier', 'Purchase', true),
  ('Aditya Technologies', 'supplier', 'Purchase', true),
  ('Aeran Steel Corporation', 'supplier', 'Purchase', true),
  ('Agrioma Life Science', 'supplier', 'Purchase', true),
  ('Akash Trading Company', 'supplier', 'Purchase', true),
  ('Alivera Animal Health  LTD', 'supplier', 'Purchase', true),
  ('Alivera Animal Health Limited', 'supplier', 'Purchase', true),
  ('Alivira Animal Health Limited', 'supplier', 'Purchase', true),
  ('Alivira Animal Health Ltd', 'supplier', 'Purchase', true),
  ('All Tech Bio Technology', 'supplier', 'Purchase', true),
  ('Alltech Biotechnolgy Pvt Ltd', 'supplier', 'Purchase', true),
  ('Alltech Biotechnology  PVT LTD', 'supplier', 'Purchase', true),
  ('Alltech Biotechnology Pvt Ltd', 'supplier', 'Purchase', true),
  ('Amarnath Enterprises', 'supplier', 'Purchase', true),
  ('Amarnath Enterprises / Surya Cem Pvt Ltd', 'supplier', 'Purchase', true),
  ('Anamika Agencies', 'supplier', 'Purchase', true),
  ('Ananta Reddy Cash', 'supplier', 'Purchase', true),
  ('Anjaneyulu  - Water Tanker', 'supplier', 'Purchase', true),
  ('Aradhya Steel & Cement Traders', 'supplier', 'Purchase', true),
  ('Aradhya Steel & Cement traders', 'supplier', 'Purchase', true),
  ('Arevin Lifesciences Pvt Ltd', 'supplier', 'Purchase', true),
  ('Aromas Pharma', 'supplier', 'Purchase', true),
  ('Aspire Industries', 'supplier', 'Purchase', true),
  ('Avitech Nutrition Pvt Ltd', 'supplier', 'Purchase', true),
  ('BBA SALES CORPORATION', 'supplier', 'Purchase', true),
  ('BBA Sales Corporation', 'supplier', 'Purchase', true),
  ('BHARAT TRADERS', 'supplier', 'Purchase', true),
  ('BHARATH Maize', 'supplier', 'Purchase', true),
  ('BLOW -CHEM & AYURVEDIC INDUSTRIES', 'supplier', 'Purchase', true),
  ('BSCPL (RAVI)', 'supplier', 'Purchase', true),
  ('BSCPL - DUST', 'supplier', 'Purchase', true),
  ('BSCPL Ravi', 'supplier', 'Purchase', true),
  ('BSPCL (Ravi)', 'supplier', 'Purchase', true),
  ('BSPL', 'supplier', 'Purchase', true),
  ('Bala Swami', 'supplier', 'Purchase', true),
  ('Balaji Automotives', 'supplier', 'Purchase', true),
  ('Balaram Automobiles', 'supplier', 'Purchase', true),
  ('Balaswami  Dozar', 'supplier', 'Purchase', true),
  ('Balaswamy Red Sand', 'supplier', 'Purchase', true),
  ('Bardhal Surendhar - Amar Singh Maize', 'supplier', 'Purchase', true),
  ('Batcha''s Furniture Castle', 'supplier', 'Purchase', true),
  ('Bengal Agrovet Private Limited', 'supplier', 'Purchase', true),
  ('Bengal Agrovet Pvt Ltd', 'supplier', 'Purchase', true),
  ('Bhabani  Bio Security', 'supplier', 'Purchase', true),
  ('Bhabani  Bio-Security', 'supplier', 'Purchase', true),
  ('Bhabani Bio Security', 'supplier', 'Purchase', true),
  ('Bhabani Bio- Security', 'supplier', 'Purchase', true),
  ('Bhabani Bio-Security', 'supplier', 'Purchase', true),
  ('Bhandari Distributors', 'supplier', 'Purchase', true),
  ('Bharat Transport CO.', 'supplier', 'Purchase', true),
  ('Bharath - Maize', 'supplier', 'Purchase', true),
  ('Bharath Maize', 'supplier', 'Purchase', true),
  ('Bhaskar Reddy/Jagadeswar Reddy', 'supplier', 'Purchase', true),
  ('Bhavani Vetenary Medical Health', 'supplier', 'Purchase', true),
  ('Bhavani Veterinary Medical Hall', 'supplier', 'Purchase', true),
  ('Bhavani Vetrniary  Medical Hall', 'supplier', 'Purchase', true),
  ('Bhuvana Nutribio Sciences', 'supplier', 'Purchase', true),
  ('Blue Print', 'supplier', 'Purchase', true),
  ('CHANDER NAIK(SAND)', 'supplier', 'Purchase', true),
  ('COCONUT BROOMS', 'supplier', 'Purchase', true),
  ('CRESENT MARKETING', 'supplier', 'Purchase', true),
  ('Cancelled', 'supplier', 'Purchase', true),
  ('Care Fire Safety - 25-26', 'supplier', 'Purchase', true),
  ('Chandan Trading Company', 'supplier', 'Purchase', true),
  ('Chandan Trading Company PVT LTD', 'supplier', 'Purchase', true),
  ('Chander Naik (Sand)', 'supplier', 'Purchase', true),
  ('Chatrapati Enterprises', 'supplier', 'Purchase', true),
  ('Chemicals & Equipment Center', 'supplier', 'Purchase', true),
  ('Chemicals & Equipments Center', 'supplier', 'Purchase', true),
  ('Concur Equipoise Pvt Ltd', 'supplier', 'Purchase', true),
  ('Crecent Marketing', 'supplier', 'Purchase', true),
  ('Crescent Marketing', 'supplier', 'Purchase', true),
  ('DAS DRUG CENTRE', 'supplier', 'Purchase', true),
  ('DEEPAK PAINTS', 'supplier', 'Purchase', true),
  ('DHANI ENTERPRISES', 'supplier', 'Purchase', true),
  ('DIAMOND FARM EQUIPMENTS', 'supplier', 'Purchase', true),
  ('Das Drug Center', 'supplier', 'Purchase', true),
  ('Das Drug Centre', 'supplier', 'Purchase', true),
  ('Das Drug Centre PVT LTD', 'supplier', 'Purchase', true),
  ('Das Drug Centre PVT Limited', 'supplier', 'Purchase', true),
  ('Das Drug Centre Private Limited', 'supplier', 'Purchase', true),
  ('Das Drug Centre Pvt Ltd', 'supplier', 'Purchase', true),
  ('Das Drug Store', 'supplier', 'Purchase', true),
  ('Deepak Paints', 'supplier', 'Purchase', true),
  ('Depla Red Bricks', 'supplier', 'Purchase', true),
  ('Dhani Enterprises', 'supplier', 'Purchase', true),
  ('Dhirendra Soya Agro PVT LTD', 'supplier', 'Purchase', true),
  ('Diamond Farm Equipment', 'supplier', 'Purchase', true),
  ('Diamond Farm Equipments', 'supplier', 'Purchase', true),
  ('Diamond Farms Equipments', 'supplier', 'Purchase', true),
  ('ELANCO INDIA PVT LTD', 'supplier', 'Purchase', true),
  ('ESHWARDAS & COMPANY', 'supplier', 'Purchase', true),
  ('Egg Bank', 'supplier', 'Purchase', true),
  ('Elanco India Pvt Ltd', 'supplier', 'Purchase', true),
  ('Empire Scientfic Surgicals', 'supplier', 'Purchase', true),
  ('FARMTECH EQUIPMENTS', 'supplier', 'Purchase', true),
  ('Farmtech Equipments', 'supplier', 'Purchase', true),
  ('Futnani Steels Private LTD', 'supplier', 'Purchase', true),
  ('Futnani Steels Pvt Ltd', 'supplier', 'Purchase', true),
  ('GMMCO Limited', 'supplier', 'Purchase', true),
  ('GURUKRUPA  GAS SERVICES', 'supplier', 'Purchase', true),
  ('Ganesh Poultry Farm Eqipments', 'supplier', 'Purchase', true),
  ('Ganesh Stationers', 'supplier', 'Purchase', true),
  ('Gangadhar Goud', 'supplier', 'Purchase', true),
  ('Gangdhar Goud', 'supplier', 'Purchase', true),
  ('Ganji Venkannah & Son''s', 'supplier', 'Purchase', true),
  ('Ganji Venkannah & Sons', 'supplier', 'Purchase', true),
  ('Gaurika Industries', 'supplier', 'Purchase', true),
  ('Gauthami Pipes Pvt Ltd', 'supplier', 'Purchase', true),
  ('Gayathri Salts', 'supplier', 'Purchase', true),
  ('Gayatri Salts', 'supplier', 'Purchase', true),
  ('Ghosh Sales & Service', 'supplier', 'Purchase', true),
  ('Ghouse', 'supplier', 'Purchase', true),
  ('Gitaa Medical Enterprise', 'supplier', 'Purchase', true),
  ('Global Chemicals Limited', 'supplier', 'Purchase', true),
  ('Goenka Proteins Private Limited', 'supplier', 'Purchase', true),
  ('GuruKrupa Gas Services', 'supplier', 'Purchase', true),
  ('Gurukrupa Gas Service', 'supplier', 'Purchase', true),
  ('Gurukrupa Gas Service Transport', 'supplier', 'Purchase', true),
  ('Gurukrupa Gas Services', 'supplier', 'Purchase', true),
  ('HACKBERRYIND', 'supplier', 'Purchase', true),
  ('HARD BROOMS', 'supplier', 'Purchase', true),
  ('HARGUN AGRO INDUSTRIES LTD', 'supplier', 'Purchase', true),
  ('HARGUN AGRO INDUSTRIES PVT LTD', 'supplier', 'Purchase', true),
  ('HEALERS ASSOCIATED', 'supplier', 'Purchase', true),
  ('HEALERS ASSOCIATES', 'supplier', 'Purchase', true),
  ('HERSTER BIOSCIENCES LIMITTED', 'supplier', 'Purchase', true),
  ('HESTAR BIOSCIENCES LIMITED', 'supplier', 'Purchase', true),
  ('HITCH HATCH FRESH PVT.LTD', 'supplier', 'Purchase', true),
  ('HITECH HATCH FRESH PVT LTD', 'supplier', 'Purchase', true),
  ('HUVEPHARMA', 'supplier', 'Purchase', true),
  ('HUVEPHARMA SEA PUNE PVT LTD', 'supplier', 'Purchase', true),
  ('Hargon Agro Industries PVT LTD', 'supplier', 'Purchase', true),
  ('Hargun Agro  Industries Pvt Ltd', 'supplier', 'Purchase', true),
  ('Hargun Agro Industies Pvt Ltd', 'supplier', 'Purchase', true),
  ('Hargun Agro Industries', 'supplier', 'Purchase', true),
  ('Hargun Agro Industries  PVT LTD -23-24', 'supplier', 'Purchase', true),
  ('Hargun Agro Industries LTD', 'supplier', 'Purchase', true),
  ('Hargun Agro Industries PVT LTD', 'supplier', 'Purchase', true),
  ('Hargun Agro Industries Pvt LTD', 'supplier', 'Purchase', true),
  ('Hargun Agro Industries Pvt Ltd', 'supplier', 'Purchase', true),
  ('Hargun Agro industries PVT LTD', 'supplier', 'Purchase', true),
  ('Hargun agro industries PVT LTD', 'supplier', 'Purchase', true),
  ('Harshitha Engineering Industries Pvt Ltd', 'supplier', 'Purchase', true),
  ('Healers  Associates', 'supplier', 'Purchase', true),
  ('Healers Associates', 'supplier', 'Purchase', true),
  ('Healers Assosiates', 'supplier', 'Purchase', true),
  ('Healrs Associates', 'supplier', 'Purchase', true),
  ('Hepsten Biosciences Limited', 'supplier', 'Purchase', true),
  ('Hester BioSciences Limited', 'supplier', 'Purchase', true),
  ('Hester Biosciences Limited', 'supplier', 'Purchase', true),
  ('Hester Biosciences Ltd', 'supplier', 'Purchase', true),
  ('Hitech Breeding Farms', 'supplier', 'Purchase', true),
  ('Hitech Hatch Fresh  Pvt Ltd', 'supplier', 'Purchase', true),
  ('Hitech Hatch Fresh Limited Hyd', 'supplier', 'Purchase', true),
  ('Hitech Hatch Fresh PVT LTD', 'supplier', 'Purchase', true),
  ('Hitech Hatch Fresh PVt LTD', 'supplier', 'Purchase', true),
  ('Hitech Hatch Fresh Pvt Ltd', 'supplier', 'Purchase', true),
  ('Hitech Hatch Fresh Pvt Ltd ( HYD)', 'supplier', 'Purchase', true),
  ('Hitech Hatch Fresh Pvt Ltd-HYD', 'supplier', 'Purchase', true),
  ('Hitech Hatch fresh Pvt Ltd - Hyd', 'supplier', 'Purchase', true),
  ('Hitech Hatchfresh Pvt Ltd', 'supplier', 'Purchase', true),
  ('Horvetech Private Limited', 'supplier', 'Purchase', true),
  ('Huvepharma', 'supplier', 'Purchase', true),
  ('Huvepharma Sea (Pune) PVT LTD', 'supplier', 'Purchase', true),
  ('Huvepharma Sea (Pune) Pvt Ltd', 'supplier', 'Purchase', true),
  ('Huvepharma Sea Pune Pvt Ltd', 'supplier', 'Purchase', true),
  ('Huvepharma Sea(PUNE) PVT LTD', 'supplier', 'Purchase', true),
  ('INDIAN HERBS SPECIALITIES', 'supplier', 'Purchase', true),
  ('ISLAVATH SHANKAR NAYAK(LOCAL MAIZE)', 'supplier', 'Purchase', true),
  ('IZDA Health Care', 'supplier', 'Purchase', true),
  ('IZDA Healthcare', 'supplier', 'Purchase', true),
  ('Industrial Equipment Centre', 'supplier', 'Purchase', true),
  ('Inernational steel Industries', 'supplier', 'Purchase', true),
  ('International Steel Industries', 'supplier', 'Purchase', true),
  ('Izda Health Care', 'supplier', 'Purchase', true),
  ('Izda Healthcare', 'supplier', 'Purchase', true),
  ('J Hathram', 'supplier', 'Purchase', true),
  ('JAI HANUMAN FABRICATION WORK', 'supplier', 'Purchase', true),
  ('JAINIL BATCHTECH HDFC', 'supplier', 'Purchase', true),
  ('JANYA.P  (WOOD )', 'supplier', 'Purchase', true),
  ('JCB Narasimha', 'supplier', 'Purchase', true),
  ('JCB Work', 'supplier', 'Purchase', true),
  ('JINDATT AGROTECH', 'supplier', 'Purchase', true),
  ('JS Enterprises', 'supplier', 'Purchase', true),
  ('Jagini Krishna Reddy', 'supplier', 'Purchase', true),
  ('Jai Hanuman Fabrication', 'supplier', 'Purchase', true),
  ('Jai Hanuman Fabrication Works', 'supplier', 'Purchase', true),
  ('Jannu', 'supplier', 'Purchase', true),
  ('Janu', 'supplier', 'Purchase', true),
  ('Janya - Fire Wood', 'supplier', 'Purchase', true),
  ('Janya - Wood', 'supplier', 'Purchase', true),
  ('Janya-Wood', 'supplier', 'Purchase', true),
  ('Jaunu', 'supplier', 'Purchase', true),
  ('Jayshree Solvex India Pvt Ltd', 'supplier', 'Purchase', true),
  ('Jayshree Solvex India Pvt Ltd 2025-26', 'supplier', 'Purchase', true),
  ('Jeco AgroVet Private Limited', 'supplier', 'Purchase', true),
  ('Jeco Agrovet Private Limited', 'supplier', 'Purchase', true),
  ('Jeco Agrovet Pvt Ltd', 'supplier', 'Purchase', true),
  ('Jeco Agrovet private Limited', 'supplier', 'Purchase', true),
  ('Jeco Nutri Chem Pvt Ltd', 'supplier', 'Purchase', true),
  ('Jeco Nutri chem Pvt Ltd', 'supplier', 'Purchase', true),
  ('Jindatt Agrotech', 'supplier', 'Purchase', true),
  ('K S R Stone Crusher', 'supplier', 'Purchase', true),
  ('K. Mahipal Reddy Maize Traders', 'supplier', 'Purchase', true),
  ('K.S.R.STONE Crusher', 'supplier', 'Purchase', true),
  ('K.S.R.STONE METALS', 'supplier', 'Purchase', true),
  ('KEMIN INDUSTRIES SOUTH ASIA PVT LTD', 'supplier', 'Purchase', true),
  ('KGN Force Auto Garage', 'supplier', 'Purchase', true),
  ('KUMAR ENTERPRISES', 'supplier', 'Purchase', true),
  ('Kalpana', 'supplier', 'Purchase', true),
  ('Kemin Industries', 'supplier', 'Purchase', true),
  ('Kemin Industries South Asia Private Limited', 'supplier', 'Purchase', true),
  ('Kemin Industries South Asia Pvt Ltd', 'supplier', 'Purchase', true),
  ('Khan Enterprises', 'supplier', 'Purchase', true),
  ('Kiran Glass', 'supplier', 'Purchase', true),
  ('Kiran Glass Handicrafts Blowing Works', 'supplier', 'Purchase', true),
  ('Kotha Shekar Reddy', 'supplier', 'Purchase', true),
  ('Kothakapu Narsimha Reddy', 'supplier', 'Purchase', true),
  ('Kothhakapu Narsimha Reddy', 'supplier', 'Purchase', true),
  ('Kotthakapu Narsimha Reddy JCB', 'supplier', 'Purchase', true),
  ('Kumar Enterprises', 'supplier', 'Purchase', true),
  ('L Jagadeswar Reddy', 'supplier', 'Purchase', true),
  ('LAXMI NARSIMHA CEMENT BRICKS', 'supplier', 'Purchase', true),
  ('LOCAL MAIZE', 'supplier', 'Purchase', true),
  ('LOCAL MAIZE (B.GURUPADAM)', 'supplier', 'Purchase', true),
  ('LOCAL MAIZE (BAIRAMONI RAMU)', 'supplier', 'Purchase', true),
  ('LOCAL MAIZE (JARPULA THULCHYA)', 'supplier', 'Purchase', true),
  ('LOCAL MAIZE (K.MALLESH)', 'supplier', 'Purchase', true),
  ('LOCAL MAIZE (KETHANATH SANDEP)', 'supplier', 'Purchase', true),
  ('LOCAL MAIZE (KETHAVATH RAMDAS)', 'supplier', 'Purchase', true),
  ('LOCAL MAIZE (KUMMARI MALLESH)', 'supplier', 'Purchase', true),
  ('LOCAL MAIZE (KUMMARI SRISHAILAM)', 'supplier', 'Purchase', true),
  ('LOCAL MAIZE (RAMAVATH SEVYA)', 'supplier', 'Purchase', true),
  ('LOCAL MAIZE (THULASI RAM)', 'supplier', 'Purchase', true),
  ('LOCAL MAIZE (V.SAVYA)', 'supplier', 'Purchase', true),
  ('LOCAL MAIZE (V.VINOD KUMAR)', 'supplier', 'Purchase', true),
  ('LOCAL PURCHASE', 'supplier', 'Purchase', true),
  ('Lachhu Nayak', 'supplier', 'Purchase', true),
  ('Lachu Nayak - Maize', 'supplier', 'Purchase', true),
  ('Lakshmi Balaji Ceramics', 'supplier', 'Purchase', true),
  ('Local purchase', 'supplier', 'Purchase', true),
  ('M R ELECTRIC CORPORATION', 'supplier', 'Purchase', true),
  ('M R Electric Corporation', 'supplier', 'Purchase', true),
  ('M/S SAI SANTHOSHINI TRADERS', 'supplier', 'Purchase', true),
  ('M/S SUSHMA TRADERS', 'supplier', 'Purchase', true),
  ('M/s. SHIVA SAI TRADERS', 'supplier', 'Purchase', true),
  ('MANDAL IMPREST', 'supplier', 'Purchase', true),
  ('MEC Diesels - Kirloskar Care', 'supplier', 'Purchase', true),
  ('MK Sales Corporation', 'supplier', 'Purchase', true),
  ('MR Crate Paper Products', 'supplier', 'Purchase', true),
  ('MR Electric Corporation', 'supplier', 'Purchase', true),
  ('MR Elelctri Corporation', 'supplier', 'Purchase', true),
  ('MRF Exclusive', 'supplier', 'Purchase', true),
  ('Maa Chamunda Marketing', 'supplier', 'Purchase', true),
  ('Mahaveer Distributors', 'supplier', 'Purchase', true),
  ('Mahendhar', 'supplier', 'Purchase', true),
  ('Mahipal Traders - Maize', 'supplier', 'Purchase', true),
  ('Maithri Solvents Pvt Ltd', 'supplier', 'Purchase', true),
  ('Mak Industries', 'supplier', 'Purchase', true),
  ('Mallikarjuna Papers', 'supplier', 'Purchase', true),
  ('Manikanta Traders', 'supplier', 'Purchase', true),
  ('Manikanta Traders Nagar Kurnool', 'supplier', 'Purchase', true),
  ('Medplus Pharmacy', 'supplier', 'Purchase', true),
  ('Meher Mahalakshmi Traders', 'supplier', 'Purchase', true),
  ('Metro Company', 'supplier', 'Purchase', true),
  ('Mitesh Ropes Industry', 'supplier', 'Purchase', true),
  ('Mitra Agencies', 'supplier', 'Purchase', true),
  ('Mohammed Ali& Sons', 'supplier', 'Purchase', true),
  ('Mohan Harware', 'supplier', 'Purchase', true),
  ('Mohan JCB-TS36A3363', 'supplier', 'Purchase', true),
  ('Moin Engineering Works', 'supplier', 'Purchase', true),
  ('Moin Pumps', 'supplier', 'Purchase', true),
  ('Moin Pumps & Spares', 'supplier', 'Purchase', true),
  ('Moin Pums & Spares', 'supplier', 'Purchase', true),
  ('More Powers', 'supplier', 'Purchase', true),
  ('More Than Solutions Pvt Ltd', 'supplier', 'Purchase', true),
  ('More than Solutions Pvt Ltd', 'supplier', 'Purchase', true),
  ('Mr.Shaikh Atikh Shaikh Mukhid', 'supplier', 'Purchase', true),
  ('My Home Industries Pvt Ltd', 'supplier', 'Purchase', true),
  ('Mysore Nandi Tarpaulins MFG CO', 'supplier', 'Purchase', true),
  ('Mysore Nandi Tarpaulins MFG Co', 'supplier', 'Purchase', true),
  ('Mysore Nandi Tarpaulins MFG.Co', 'supplier', 'Purchase', true),
  ('NANDI ARTS STATIONARY', 'supplier', 'Purchase', true),
  ('NENAVATH NARSIMHA (BRICKS)', 'supplier', 'Purchase', true),
  ('NEWS PAPERS', 'supplier', 'Purchase', true),
  ('NOVUS', 'supplier', 'Purchase', true),
  ('Naga Lingam', 'supplier', 'Purchase', true),
  ('Nandu Paper Shop', 'supplier', 'Purchase', true),
  ('Narasimha - Red Bricks', 'supplier', 'Purchase', true),
  ('Narasimha Nayak', 'supplier', 'Purchase', true),
  ('Narayana Agro Oils Pvt Ltd', 'supplier', 'Purchase', true),
  ('Narsimha', 'supplier', 'Purchase', true),
  ('Narsimha JCB KR Pally Red Bricks', 'supplier', 'Purchase', true),
  ('Narsimha Reddy/Anand Reddy', 'supplier', 'Purchase', true),
  ('Natural Herbs & Formulation Pvt Ltd', 'supplier', 'Purchase', true),
  ('Natural Herbs & Formulations Pvt Ltd', 'supplier', 'Purchase', true),
  ('Neethin Traders', 'supplier', 'Purchase', true),
  ('New Neela Traders', 'supplier', 'Purchase', true),
  ('New Reliable Pesticides', 'supplier', 'Purchase', true),
  ('New Shri Swami Samarth Transport', 'supplier', 'Purchase', true),
  ('New Shri Swami Samarth Transport - Soya Transport', 'supplier', 'Purchase', true),
  ('New Shri Swami Samrath Transport', 'supplier', 'Purchase', true),
  ('Nilkamal Limited', 'supplier', 'Purchase', true),
  ('Nutan Medical Hall', 'supplier', 'Purchase', true),
  ('Nutan Medicals Veterinary', 'supplier', 'Purchase', true),
  ('Nutan Medicals Veterinary Division', 'supplier', 'Purchase', true),
  ('Nutech Bioscience India Pvt Ltd', 'supplier', 'Purchase', true),
  ('Nutridian Animal Health-Hyd Branch', 'supplier', 'Purchase', true),
  ('OM SAI KRISHNA ENTERPRISES', 'supplier', 'Purchase', true),
  ('Olive Enterprises', 'supplier', 'Purchase', true),
  ('Om Sai Krishna Enterprises', 'supplier', 'Purchase', true),
  ('Oriental Hardware Company', 'supplier', 'Purchase', true),
  ('P Janya', 'supplier', 'Purchase', true),
  ('P Janya - Wood', 'supplier', 'Purchase', true),
  ('P Janya Fire Wood', 'supplier', 'Purchase', true),
  ('P Janya Wood', 'supplier', 'Purchase', true),
  ('PARAMESHWARIDEVI', 'supplier', 'Purchase', true),
  ('PP &  B Mart PVT LTD', 'supplier', 'Purchase', true),
  ('PP & B MART PVT LTD', 'supplier', 'Purchase', true),
  ('PP & B Mart Pvt Ltd', 'supplier', 'Purchase', true),
  ('PP& B Mart PVT LTD', 'supplier', 'Purchase', true),
  ('PP&B Mart Pvt ltd', 'supplier', 'Purchase', true),
  ('PRAVALLIKA CARTONS', 'supplier', 'Purchase', true),
  ('PSL Polymers', 'supplier', 'Purchase', true),
  ('PURCHASE OF PACKING MATERIAL', 'supplier', 'Purchase', true),
  ('Padmaja Poultry Agencies', 'supplier', 'Purchase', true),
  ('Parameshwari Devi', 'supplier', 'Purchase', true),
  ('Parameshwaridevi Seeds & Pestcides', 'supplier', 'Purchase', true),
  ('Parameshwaridevi Seeds & Pesticides', 'supplier', 'Purchase', true),
  ('Parasnath  Agro', 'supplier', 'Purchase', true),
  ('Parasnath Agro', 'supplier', 'Purchase', true),
  ('Parimala Agencies', 'supplier', 'Purchase', true),
  ('Pathlavath Narasimha - JCB', 'supplier', 'Purchase', true),
  ('Pavani Hybrid Seeds', 'supplier', 'Purchase', true),
  ('Payal Electricals', 'supplier', 'Purchase', true),
  ('Penta Reddy', 'supplier', 'Purchase', true),
  ('Plasto Marketing Agencies', 'supplier', 'Purchase', true),
  ('Plasto Marketing agencies', 'supplier', 'Purchase', true),
  ('Power Links', 'supplier', 'Purchase', true),
  ('Power Links - Kirlosakar Care', 'supplier', 'Purchase', true),
  ('Power Links - Kirloskar Care', 'supplier', 'Purchase', true),
  ('Power links Infra Tech Pvt Ltd', 'supplier', 'Purchase', true),
  ('Prakash Stationers', 'supplier', 'Purchase', true),
  ('Pravallika Cartons', 'supplier', 'Purchase', true),
  ('Pravallika Cartoons', 'supplier', 'Purchase', true),
  ('Provimi Animal Nutrition India PVT LTD', 'supplier', 'Purchase', true),
  ('Provimi Animal Nutrition India Pvt Ltd', 'supplier', 'Purchase', true),
  ('Provimi Animal Nutrition india Pvt Ltd', 'supplier', 'Purchase', true),
  ('Prudwi Tyres', 'supplier', 'Purchase', true),
  ('Quality Pvc Pipes Pvt Ltd', 'supplier', 'Purchase', true),
  ('Quest Agrovet Services Pvt Ltd', 'supplier', 'Purchase', true),
  ('RAMA COCONUT COMPANY', 'supplier', 'Purchase', true),
  ('REGAL ENGINEERING CORPORATION', 'supplier', 'Purchase', true),
  ('RIDHI SIDHI CORPORATION', 'supplier', 'Purchase', true),
  ('RK Enterprises', 'supplier', 'Purchase', true),
  ('RR Agros', 'supplier', 'Purchase', true),
  ('RR VETERINARY HELTH CARE PVT LTD', 'supplier', 'Purchase', true),
  ('RR Veterianary Health Care Pvt Ltd', 'supplier', 'Purchase', true),
  ('RR Veterinary Health Care PVT LTD', 'supplier', 'Purchase', true),
  ('RR Veterinary Health Care Pvt Ltd', 'supplier', 'Purchase', true),
  ('RR Veterinary health Care Pvt Ltd', 'supplier', 'Purchase', true),
  ('RR Veternary Health Care Pvt Ltd', 'supplier', 'Purchase', true),
  ('RTITS Pvt Ltd', 'supplier', 'Purchase', true),
  ('RUDRA MINERALLS', 'supplier', 'Purchase', true),
  ('Radhakrishna Marketings', 'supplier', 'Purchase', true),
  ('Raghavendra Agencies', 'supplier', 'Purchase', true),
  ('Raghavendra Electrical Winding Works', 'supplier', 'Purchase', true),
  ('Raghavendra Electrical winding works', 'supplier', 'Purchase', true),
  ('Raghvendera Agencies', 'supplier', 'Purchase', true),
  ('Raghvendra Agencies', 'supplier', 'Purchase', true),
  ('Raghvendra Electrical Winding Works', 'supplier', 'Purchase', true),
  ('Rahul Sales', 'supplier', 'Purchase', true),
  ('Raj Combines Solutions', 'supplier', 'Purchase', true),
  ('Raju', 'supplier', 'Purchase', true),
  ('Raju & Raju Herbals', 'supplier', 'Purchase', true),
  ('Ram Das', 'supplier', 'Purchase', true),
  ('Rama Coconut Company', 'supplier', 'Purchase', true),
  ('Ramdev Marketing', 'supplier', 'Purchase', true),
  ('Ramesh Naik (Sand)', 'supplier', 'Purchase', true),
  ('Ravioza Biotech', 'supplier', 'Purchase', true),
  ('Reddy Auto Mobiles', 'supplier', 'Purchase', true),
  ('Reddy Automobiles', 'supplier', 'Purchase', true),
  ('Regal Engineering  Corporation -24-25', 'supplier', 'Purchase', true),
  ('Regal Engineering Corporation', 'supplier', 'Purchase', true),
  ('Regen Biocorps Ahi Pvt Ltd', 'supplier', 'Purchase', true),
  ('Repro Engineering Corporation', 'supplier', 'Purchase', true),
  ('Rex Automobiles', 'supplier', 'Purchase', true),
  ('Rk Worldinfocom Private Limited', 'supplier', 'Purchase', true),
  ('Rudra Mineralls', 'supplier', 'Purchase', true),
  ('Rudra Minerals', 'supplier', 'Purchase', true),
  ('Rudra minerals', 'supplier', 'Purchase', true),
  ('S.M  ENTERPRISES', 'supplier', 'Purchase', true),
  ('SAG AGRO COMMODLTLES', 'supplier', 'Purchase', true),
  ('SAI KIRAN MEDICAL AGENCIES', 'supplier', 'Purchase', true),
  ('SAI SANTHOSHINI TRADERS', 'supplier', 'Purchase', true),
  ('SB Plastic Bags', 'supplier', 'Purchase', true),
  ('SHIVA PACKING', 'supplier', 'Purchase', true),
  ('SHRINIVASA AGRO FOODS PVT.LTD', 'supplier', 'Purchase', true),
  ('SLC Vinayaka Enterprises', 'supplier', 'Purchase', true),
  ('SM Transport', 'supplier', 'Purchase', true),
  ('SNEHA FARMS PVT LTD', 'supplier', 'Purchase', true),
  ('SPRINGS', 'supplier', 'Purchase', true),
  ('SRI BALAJI TRADERS', 'supplier', 'Purchase', true),
  ('SRI LAXMI DURGA TRADERS', 'supplier', 'Purchase', true),
  ('SRI LAXMI NARASIMHA - Cement Bricks', 'supplier', 'Purchase', true),
  ('SRI LAXMI NARSIMHA - Cement Bricks', 'supplier', 'Purchase', true),
  ('SRI SAI CHARANA CHEMICALS', 'supplier', 'Purchase', true),
  ('SRI SAI POULTRY EQUIPMWNTS', 'supplier', 'Purchase', true),
  ('SRI SAI PULP & PACK', 'supplier', 'Purchase', true),
  ('SRI SANTOSH SOUTHERN CHEMICALS', 'supplier', 'Purchase', true),
  ('SS TECHNOLOGY', 'supplier', 'Purchase', true),
  ('STALEN SOUTH ASIA PVT. LTD', 'supplier', 'Purchase', true),
  ('STATS SPECIALITY PRODUCTS PVT LTD', 'supplier', 'Purchase', true),
  ('STONE ROCK CREAM LLP', 'supplier', 'Purchase', true),
  ('SURANA MARKETING', 'supplier', 'Purchase', true),
  ('SURYACEM (P) LTD', 'supplier', 'Purchase', true),
  ('SUSHMA TRADERS', 'supplier', 'Purchase', true),
  ('Sachin Interational Proteins Pvt Ltd', 'supplier', 'Purchase', true),
  ('Sachin International Proteins PVT LTD', 'supplier', 'Purchase', true),
  ('Sachin International Proteins Pvt Ltd', 'supplier', 'Purchase', true),
  ('Sachin International Protiens Pvt Ltd', 'supplier', 'Purchase', true),
  ('Sachin International proteins Pvt Ltd', 'supplier', 'Purchase', true),
  ('Sai C R V Packaging', 'supplier', 'Purchase', true),
  ('Sai CRV Packaging', 'supplier', 'Purchase', true),
  ('Sai Durga Agro Tech  Industries', 'supplier', 'Purchase', true),
  ('Sai Durga Agro Tech Industries', 'supplier', 'Purchase', true),
  ('Sai Durga Agro Tech Industries 23-24', 'supplier', 'Purchase', true),
  ('Sai Durga Tech Industries', 'supplier', 'Purchase', true),
  ('Sai Electricals', 'supplier', 'Purchase', true),
  ('Sai Kiran Medical Agencies', 'supplier', 'Purchase', true),
  ('Sai Kiran Medical Agencies 2024-25', 'supplier', 'Purchase', true),
  ('Sai Krishna Medical Agencies', 'supplier', 'Purchase', true),
  ('Sai Krishna Plastic Industries', 'supplier', 'Purchase', true),
  ('Sai Ram Electrical Motor Rewinding Works', 'supplier', 'Purchase', true),
  ('Sai Sanothshini Traders', 'supplier', 'Purchase', true),
  ('Sai Santhoshini Traders', 'supplier', 'Purchase', true),
  ('Sai Santhoshini Traders DSR', 'supplier', 'Purchase', true),
  ('Sai Santhosini Traders', 'supplier', 'Purchase', true),
  ('Sai Santosh Southern Minerals', 'supplier', 'Purchase', true),
  ('Sai Santoshini Traders', 'supplier', 'Purchase', true),
  ('Sai Shakthi Packaging Industries', 'supplier', 'Purchase', true),
  ('Sai Shakthi Packaging industries', 'supplier', 'Purchase', true),
  ('Sai Shakti Packaging  Industries', 'supplier', 'Purchase', true),
  ('Sai Shakti Packaging Industries', 'supplier', 'Purchase', true),
  ('Sai santhoshini Traders', 'supplier', 'Purchase', true),
  ('Sai santhosini Traders', 'supplier', 'Purchase', true),
  ('Sai santoshine Traders', 'supplier', 'Purchase', true),
  ('Sana Cooling System', 'supplier', 'Purchase', true),
  ('Sanna Cooling System', 'supplier', 'Purchase', true),
  ('Sapience Agribusiness Consulting', 'supplier', 'Purchase', true),
  ('Sapience Agribusiness Consulting LLP', 'supplier', 'Purchase', true),
  ('Sapience Agribusiness Consulting LLP - Chennai', 'supplier', 'Purchase', true),
  ('Saradhi Agrovet', 'supplier', 'Purchase', true),
  ('Savaria Oil Suppliers', 'supplier', 'Purchase', true),
  ('Sayeed Brothers', 'supplier', 'Purchase', true),
  ('Sharp Electricals & Apliances', 'supplier', 'Purchase', true),
  ('Shekar Reddy - Birds Shifting', 'supplier', 'Purchase', true),
  ('Shekar Reddy DCM 2', 'supplier', 'Purchase', true),
  ('Shekar reddy  Tractor trips', 'supplier', 'Purchase', true),
  ('Shiva Packaging', 'supplier', 'Purchase', true),
  ('Shiva Sai Brokers', 'supplier', 'Purchase', true),
  ('Shiva Shakti Steel tubes', 'supplier', 'Purchase', true),
  ('Shiva Shankar Traders', 'supplier', 'Purchase', true),
  ('Shivmauli Traders', 'supplier', 'Purchase', true),
  ('Shree NM Electricals Ltd', 'supplier', 'Purchase', true),
  ('Shree Ratna Traders', 'supplier', 'Purchase', true),
  ('Shri Mallikarjun Trading Company', 'supplier', 'Purchase', true),
  ('Shri Nandi Trading Company', 'supplier', 'Purchase', true),
  ('Shrinivasa Agro  Foods Pvt Ltd', 'supplier', 'Purchase', true),
  ('Shrinivasa Agro Foods', 'supplier', 'Purchase', true),
  ('Shrinivasa Agro Foods PVT LTD', 'supplier', 'Purchase', true),
  ('Shrinivasa Agro Foods Pvt LTD', 'supplier', 'Purchase', true),
  ('Shrinivasa Agro Foods Pvt Ltd', 'supplier', 'Purchase', true),
  ('Shrinivasa Cattle Feeds PVT.LTD', 'supplier', 'Purchase', true),
  ('Shwetha Enterprises', 'supplier', 'Purchase', true),
  ('Shyam Enterprises', 'supplier', 'Purchase', true),
  ('Sneha  Farms PVT LTD', 'supplier', 'Purchase', true),
  ('Sneha Farms', 'supplier', 'Purchase', true),
  ('Sneha Farms PVT LTD', 'supplier', 'Purchase', true),
  ('Sneha Farms Pvt Ltd', 'supplier', 'Purchase', true),
  ('Sony Enterprises, HYD.', 'supplier', 'Purchase', true),
  ('Sree Mahalakshmi Packaging', 'supplier', 'Purchase', true),
  ('Sree Mahaveer Enginnering', 'supplier', 'Purchase', true),
  ('Sree NM Electricals Ltd', 'supplier', 'Purchase', true),
  ('Sri Ambika Cement & Steels', 'supplier', 'Purchase', true),
  ('Sri Balaji Surgicals', 'supplier', 'Purchase', true),
  ('Sri Balaji Traders', 'supplier', 'Purchase', true),
  ('Sri Chakra rubbers', 'supplier', 'Purchase', true),
  ('Sri Divya Shakti Steels', 'supplier', 'Purchase', true),
  ('Sri Hari Electricals', 'supplier', 'Purchase', true),
  ('Sri Jalaram Enterprises', 'supplier', 'Purchase', true),
  ('Sri Krishna Agencies', 'supplier', 'Purchase', true),
  ('Sri Lakshmi Narsimha Traders', 'supplier', 'Purchase', true),
  ('Sri Laxmi Narasimha - Cement Bricks', 'supplier', 'Purchase', true),
  ('Sri Laxmi Narasimha HVAC Systems', 'supplier', 'Purchase', true),
  ('Sri Laxmi Narsimha', 'supplier', 'Purchase', true),
  ('Sri Laxmi Narsimha - Cement Bricks', 'supplier', 'Purchase', true),
  ('Sri Laxmma Devi Maize - Lachu', 'supplier', 'Purchase', true),
  ('Sri Mahalaxmi Electrical & Electronics', 'supplier', 'Purchase', true),
  ('Sri Parikshith Garuda Enterprises', 'supplier', 'Purchase', true),
  ('Sri Raghavendra Enterprises', 'supplier', 'Purchase', true),
  ('Sri Rama Enterprises', 'supplier', 'Purchase', true),
  ('Sri Sai Electricals', 'supplier', 'Purchase', true),
  ('Sri Sai Enerprises', 'supplier', 'Purchase', true),
  ('Sri Sai Hardware New Hyderabad Trade Centre', 'supplier', 'Purchase', true),
  ('Sri Sai Krupa Traders', 'supplier', 'Purchase', true),
  ('Sri Sai Poultry', 'supplier', 'Purchase', true),
  ('Sri Sai Poultry Eqiumment', 'supplier', 'Purchase', true),
  ('Sri Sai Poultry Equiments', 'supplier', 'Purchase', true),
  ('Sri Sai Poultry Equipments', 'supplier', 'Purchase', true),
  ('Sri Sai Poutry Equipments', 'supplier', 'Purchase', true),
  ('Sri Sai Pulp & Pack', 'supplier', 'Purchase', true),
  ('Sri Sai Ram Packaging Products', 'supplier', 'Purchase', true),
  ('Sri Santhosh Soputhern Minerals', 'supplier', 'Purchase', true),
  ('Sri Santhosh Southern Chemicals', 'supplier', 'Purchase', true),
  ('Sri Santhosh Southern Minerals', 'supplier', 'Purchase', true),
  ('Sri Santosh Southern Chemicals', 'supplier', 'Purchase', true),
  ('Sri Santosh Southern Minerals', 'supplier', 'Purchase', true),
  ('Sri Santosh Southern minerals', 'supplier', 'Purchase', true),
  ('Sri Shiva Sai Enterprises', 'supplier', 'Purchase', true),
  ('Sri Shiva Sai Industries', 'supplier', 'Purchase', true),
  ('Sri Vasavi Traders', 'supplier', 'Purchase', true),
  ('Sri Veereshwara and Company', 'supplier', 'Purchase', true),
  ('Sri Vengamamba Water Supply (Gangdhar Goud)', 'supplier', 'Purchase', true),
  ('Sri Venkateshwara Packaging', 'supplier', 'Purchase', true),
  ('Sri Venkteshwara Packaging', 'supplier', 'Purchase', true),
  ('Sri sai Poultry Equipments', 'supplier', 'Purchase', true),
  ('SriSailam', 'supplier', 'Purchase', true),
  ('Srigiri Saraswathi', 'supplier', 'Purchase', true),
  ('Srigiri Saraswathi Maize', 'supplier', 'Purchase', true),
  ('Srinivasa Agro Foods Pvt Ltd', 'supplier', 'Purchase', true),
  ('Stallen South Asia Pvt Ltd', 'supplier', 'Purchase', true),
  ('Stats Speciality Products Pvt Ltd', 'supplier', 'Purchase', true),
  ('Sumit Industries', 'supplier', 'Purchase', true),
  ('Sun Jyothi Electrical and Engineering', 'supplier', 'Purchase', true),
  ('Sunways Bio Science LLP', 'supplier', 'Purchase', true),
  ('Sunways Bio-Science LLP', 'supplier', 'Purchase', true),
  ('Supreme Equipments Pvt Ltd', 'supplier', 'Purchase', true),
  ('Supreme Vet Chem Products Pvt .Ltd', 'supplier', 'Purchase', true),
  ('Supreme Vetchem Products Pvt Ltd', 'supplier', 'Purchase', true),
  ('Surya Cem Private Limited', 'supplier', 'Purchase', true),
  ('Surya Cem Pvt Ltd', 'supplier', 'Purchase', true),
  ('Surya Cem.Pvt Ltd', 'supplier', 'Purchase', true),
  ('Sushma Traders', 'supplier', 'Purchase', true),
  ('Symbio Nutrients', 'supplier', 'Purchase', true),
  ('TARA ENTERPRISES', 'supplier', 'Purchase', true),
  ('TRIOS Rubber crafts Kottayam', 'supplier', 'Purchase', true),
  ('TROUWNUTRITION INDIA PVT LTD', 'supplier', 'Purchase', true),
  ('Takur Rajender', 'supplier', 'Purchase', true),
  ('Takur Rajender - Water Tanker', 'supplier', 'Purchase', true),
  ('Tara Enterprises', 'supplier', 'Purchase', true),
  ('The Balram Automobiles', 'supplier', 'Purchase', true),
  ('Tools & Spares Corporation', 'supplier', 'Purchase', true),
  ('Trios Rubber Crafts kottayam', 'supplier', 'Purchase', true),
  ('Trouw Nutrition', 'supplier', 'Purchase', true),
  ('Trouw Nutrition India Private Limited', 'supplier', 'Purchase', true),
  ('Trouw Nutrition India Pvt Ltd', 'supplier', 'Purchase', true),
  ('United Electronics', 'supplier', 'Purchase', true),
  ('Universal Marketing', 'supplier', 'Purchase', true),
  ('Universal Motorcycle& Hardware Stores', 'supplier', 'Purchase', true),
  ('Upadrasta Brothers', 'supplier', 'Purchase', true),
  ('Uttara Foods & Feeds Pvt Ltd', 'supplier', 'Purchase', true),
  ('VARSHA MULTITECH', 'supplier', 'Purchase', true),
  ('VENKATESHWARA MARKETING', 'supplier', 'Purchase', true),
  ('VES - SPA', 'supplier', 'Purchase', true),
  ('VES SPA', 'supplier', 'Purchase', true),
  ('VES-SPA', 'supplier', 'Purchase', true),
  ('VET INDIA PHARMACEUTICALS', 'supplier', 'Purchase', true),
  ('VINOD KUMAR (LOCAL MAIZE)', 'supplier', 'Purchase', true),
  ('Vagdevi Industries', 'supplier', 'Purchase', true),
  ('Vaishnavi Irrgation System', 'supplier', 'Purchase', true),
  ('Vaishnavi Irrigation Systems', 'supplier', 'Purchase', true),
  ('Vardhaman Kitchen World', 'supplier', 'Purchase', true),
  ('Varsha Multitech', 'supplier', 'Purchase', true),
  ('Varun Agencies', 'supplier', 'Purchase', true),
  ('Vejalla Dileep', 'supplier', 'Purchase', true),
  ('Venco Research & Breeding Farm Pvt Ltd', 'supplier', 'Purchase', true),
  ('Venco Research & Breeding Farm Pvt Ltd (Venco Veeralapally Hatchery)', 'supplier', 'Purchase', true),
  ('Venco Research & Breeding Farm Pvt Ltd (Venco Vemula Hatchery)', 'supplier', 'Purchase', true),
  ('Venkateshwara B.V.Biocorp Pvt Ltd', 'supplier', 'Purchase', true),
  ('Venkateshwara B.V.Biocorp Pvt Ltd. Bio-Tech Division', 'supplier', 'Purchase', true),
  ('Venkateshwara Hatcheries Pvt Ltd', 'supplier', 'Purchase', true),
  ('Venkateshwara Marketing', 'supplier', 'Purchase', true),
  ('Venkateshwara Marketing 2024-25', 'supplier', 'Purchase', true),
  ('Venkateswara B V Bio Corp Pvt Ltd', 'supplier', 'Purchase', true),
  ('Venkateswara B V BiocorpPvt Ltd', 'supplier', 'Purchase', true),
  ('Venkateswara B.V Crop', 'supplier', 'Purchase', true),
  ('Venkateswara BV Bio corp Pvt Ltd', 'supplier', 'Purchase', true),
  ('Venkateswara Enterprises', 'supplier', 'Purchase', true),
  ('Venkateswara Hatcheries Pvt Ltd', 'supplier', 'Purchase', true),
  ('Venkateswara Hatcheries Pvt Lyd', 'supplier', 'Purchase', true),
  ('Venkateswara Vet Health Care Pvt Ltd', 'supplier', 'Purchase', true),
  ('Venkateswara Weighing Services', 'supplier', 'Purchase', true),
  ('Venkateswara hatcheries Pvt Ltd', 'supplier', 'Purchase', true),
  ('Venktateshwara Marketing', 'supplier', 'Purchase', true),
  ('Venkteshwara B V Biocorp Pvt Ltd', 'supplier', 'Purchase', true),
  ('Venkteshwara Hatcheries', 'supplier', 'Purchase', true),
  ('Venkteshwara Hatcheries Pvt Ltd', 'supplier', 'Purchase', true),
  ('Venkteshwara Hatcheries Pvt ltd', 'supplier', 'Purchase', true),
  ('Venkteshwara Marketing', 'supplier', 'Purchase', true),
  ('Venkteswar Systems', 'supplier', 'Purchase', true),
  ('Venkteswara  Hatcheries PVT LTD', 'supplier', 'Purchase', true),
  ('Venkteswara  Marketing', 'supplier', 'Purchase', true),
  ('Venkteswara B V Biocorp Pvt Ltd', 'supplier', 'Purchase', true),
  ('Venkteswara B.V Biocorp Pvt Ltd-Hitech Dev', 'supplier', 'Purchase', true),
  ('Venkteswara B.V.BioCorp Privaate Limited', 'supplier', 'Purchase', true),
  ('Venkteswara B.V.BioCorp Private Limited', 'supplier', 'Purchase', true),
  ('Venkteswara B.V.Biocorp Private Limited', 'supplier', 'Purchase', true),
  ('Venkteswara B.V.Biocorp Pvt Ltd', 'supplier', 'Purchase', true),
  ('Venkteswara BV Biocorp PVT LTD', 'supplier', 'Purchase', true),
  ('Venkteswara BV Biocorp Pvt Ltd', 'supplier', 'Purchase', true),
  ('Venkteswara Hatcheries', 'supplier', 'Purchase', true),
  ('Venkteswara Hatcheries HYD Division', 'supplier', 'Purchase', true),
  ('Venkteswara Hatcheries PVT Limited', 'supplier', 'Purchase', true),
  ('Venkteswara Hatcheries PVt LTD', 'supplier', 'Purchase', true),
  ('Venkteswara Hatcheries Pvt Ltd', 'supplier', 'Purchase', true),
  ('Venkteswara Hatcheries Pvt Ltd-Vacc Div', 'supplier', 'Purchase', true),
  ('Venkteswara Marketing', 'supplier', 'Purchase', true),
  ('Venkteswara Vet Health Care Pvt Ltd', 'supplier', 'Purchase', true),
  ('Venkteswara Weighing Services', 'supplier', 'Purchase', true),
  ('Venky''s AHP Division', 'supplier', 'Purchase', true),
  ('Venky''s India Limited-AHP Division', 'supplier', 'Purchase', true),
  ('Venky''s India Pvt Ltd', 'supplier', 'Purchase', true),
  ('Venkys (India) International Division', 'supplier', 'Purchase', true),
  ('Venkys (India) Limited AHP Division HYD', 'supplier', 'Purchase', true),
  ('Venkys (India) Limited AHPDIVISION', 'supplier', 'Purchase', true),
  ('Venkys (india) Limited AHP Division Hyderabad', 'supplier', 'Purchase', true),
  ('Venkys India Limited', 'supplier', 'Purchase', true),
  ('Venkys India Limited AHP Division', 'supplier', 'Purchase', true),
  ('Venkys India Ltd - AHP Div', 'supplier', 'Purchase', true),
  ('Ventri Biologicals Division of Venkateshwara Hatcheries Private Limited', 'supplier', 'Purchase', true),
  ('Ves-Spa', 'supplier', 'Purchase', true),
  ('Vespa', 'supplier', 'Purchase', true),
  ('Vet India Pharmaceticals', 'supplier', 'Purchase', true),
  ('Vet India Pharmaceuticals', 'supplier', 'Purchase', true),
  ('Vet India Pharmaceyticals', 'supplier', 'Purchase', true),
  ('Vibha Enterprises', 'supplier', 'Purchase', true),
  ('Vighnaharta Transline', 'supplier', 'Purchase', true),
  ('Vijaya Lakshmi Enterprises', 'supplier', 'Purchase', true),
  ('Vijaya Laxmi Enterprises', 'supplier', 'Purchase', true),
  ('Vijaya Lkshmi Enterprises', 'supplier', 'Purchase', true),
  ('Vikas & CO', 'supplier', 'Purchase', true),
  ('Visaka Industries Limited', 'supplier', 'Purchase', true),
  ('VishNu Trading Compay', 'supplier', 'Purchase', true),
  ('Vishal Peripherals', 'supplier', 'Purchase', true),
  ('Vishnu Trading Co', 'supplier', 'Purchase', true),
  ('Vishnu Trading Co.', 'supplier', 'Purchase', true),
  ('WE CARE ANIMAL HEALTH', 'supplier', 'Purchase', true),
  ('We Care Animal Health', 'supplier', 'Purchase', true),
  ('We Care Animal Health Limited', 'supplier', 'Purchase', true),
  ('We care Animal Health', 'supplier', 'Purchase', true),
  ('Western Hybrid Seeds', 'supplier', 'Purchase', true),
  ('Yallalingeshwar Trading Company', 'supplier', 'Purchase', true),
  ('Yenmad Industries', 'supplier', 'Purchase', true),
  ('Yes Babu', 'supplier', 'Purchase', true),
  ('ZEUS BIOTECH PVT LTD', 'supplier', 'Purchase', true),
  ('Zeus Biotech PVT LTD', 'supplier', 'Purchase', true),
  ('Zeus Biotech Pvt Ltd', 'supplier', 'Purchase', true),
  ('hitech Hatchfresh Pvt Ltd', 'supplier', 'Purchase', true)
ON CONFLICT ON CONSTRAINT grn_unique_record DO NOTHING;
