-- Migration 029: Additional breeder formulas (PL3-N, PL4-N, PL5-N, PL6-N) + Vaccination schedule master

-- ── Vaccination schedule master table ────────────────────────────
CREATE TABLE IF NOT EXISTS public.vaccination_schedule (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  schedule_name TEXT NOT NULL DEFAULT 'Narendra Breeder',
  sno INTEGER NOT NULL,
  age_label TEXT NOT NULL,
  vaccine_name TEXT NOT NULL,
  dose TEXT,
  route TEXT,
  product TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Seed new production formulas ─────────────────────────────────

INSERT INTO public.feed_formulas (formula_code, formula_name, flock_type, age_week_from, age_week_to, version, notes)
VALUES
  ('PL3-N', '5% to 35th week',     'Breeder', NULL, 35,   3, 'From 5% production to 35th week of age'),
  ('PL4-N', '36th week to 50th week','Breeder',36,   50,   3, 'From 36th week to 50th week of age'),
  ('PL5-N', '51st week to cullings','Breeder', 51,   NULL, 3, 'From 50th week of age to cullings'),
  ('PL6-N', 'Male Feed Formulation','Breeder', NULL, NULL, 3, 'Male birds')
ON CONFLICT DO NOTHING;

-- PL3-N ingredients (5% to 35th week)
WITH f AS (SELECT id FROM public.feed_formulas WHERE formula_code='PL3-N' LIMIT 1)
INSERT INTO public.feed_formula_ingredients (formula_id, ingredient_code, ingredient_name, percentage, kg_per_1000, sort_order) VALUES
  ((SELECT id FROM f), '11',   'MAIZE-12%Moisture',                   70.9,  708.99, 1),
  ((SELECT id FROM f), '15',   'RB OIl (5%FFA Max.)',                 0.90,  9.00,   2),
  ((SELECT id FROM f), '24',   'SOYA DOC-(46%CP)',                    18.2,  182.73, 3),
  ((SELECT id FROM f), '41',   'L SP-36.50%-Calcium-Gaurika',         4.00,  40.00,  4),
  ((SELECT id FROM f), '51',   'SALT-(Ankur)',                        0.21,  2.11,   5),
  ((SELECT id FROM f), '54',   'L-LYSINE-78%',                        0.08,  0.78,   6),
  ((SELECT id FROM f), '55',   'DLM/Rhod NP99',                       0.15,  1.50,   7),
  ((SELECT id FROM f), '56',   'SODA BICARB-Tata food grade',         0.23,  2.32,   8),
  ((SELECT id FROM f), '59',   'Microvit-C-35%/Rovimix Stay-C',       0.02,  0.20,   9),
  ((SELECT id FROM f), '60',   'Toxifin-360Dry(Kemin)',               0.13,  1.25,   10),
  ((SELECT id FROM f), '63',   'Phygest-10000-(Kemin)',               0.01,  0.10,   11),
  ((SELECT id FROM f), '77',   'Choline Chl-60%-(Jubliant/Balaji)',   0.13,  1.25,   12),
  ((SELECT id FROM f), '78',   'Kemzyme Protease-(Kemin)',            0.03,  0.25,   13),
  ((SELECT id FROM f), '82',   'Saf-Manans (Phileo)',                 0.03,  0.30,   14),
  ((SELECT id FROM f), '95',   'Breed Vitami-0.10%-Trow/DSM/Adiss',  0.10,  1.00,   15),
  ((SELECT id FROM f), '101',  'NEOLINC-Ravioza (L10+N10%)',          0.02,  0.20,   16),
  ((SELECT id FROM f), '163',  'AMINO-GABA-20% (CPBIO)',              0.03,  0.30,   17),
  ((SELECT id FROM f), '201',  'DCAD-Arm and Hammer',                 0.07,  0.70,   18),
  ((SELECT id FROM f), '238',  'Breeder In-TM-Avitech(Avimin)',       0.15,  1.50,   19),
  ((SELECT id FROM f), '301',  'Oregostim-1X-Saife-Vet',             0.03,  0.30,   20),
  ((SELECT id FROM f), '302',  'MCP-22%-Phos',                        1.00,  9.97,   21),
  ((SELECT id FROM f), '303',  'Shell Grit-36% Ca(Gaurika)',          3.24,  32.36,  22),
  ((SELECT id FROM f), '400',  '40 degree-Sunways',                   0.08,  0.75,   23),
  ((SELECT id FROM f), '0001', 'Kemtrace Supreme-Kemin',              0.08,  0.80,   24),
  ((SELECT id FROM f), '91.5', 'Vitamin-E-50%Rovimix',                0.02,  0.15,   25),
  ((SELECT id FROM f), '91.9', 'Buti Pearl(Kemin)',                   0.05,  0.50,   26),
  ((SELECT id FROM f), '92.5', 'Hepatocare(Versa)',                   0.05,  0.50,   27),
  ((SELECT id FROM f), '92.9', 'Endox-T Dry',                        0.02,  0.18,   28);

-- PL4-N ingredients (36th to 50th week)
WITH f AS (SELECT id FROM public.feed_formulas WHERE formula_code='PL4-N' LIMIT 1)
INSERT INTO public.feed_formula_ingredients (formula_id, ingredient_code, ingredient_name, percentage, kg_per_1000, sort_order) VALUES
  ((SELECT id FROM f), '11',   'MAIZE-12%Moisture',                   74.2,  742.45, 1),
  ((SELECT id FROM f), '15',   'RB OIl (5%FFA Max.)',                 0.54,  5.41,   2),
  ((SELECT id FROM f), '24',   'SOYA DOC-(46%CP)',                    15.1,  151.36, 3),
  ((SELECT id FROM f), '41',   'L SP-36.50%-Calcium-Gaurika',         4.00,  40.00,  4),
  ((SELECT id FROM f), '51',   'SALT-(Ankur)',                        0.23,  2.32,   5),
  ((SELECT id FROM f), '54',   'L-LYSINE-78%',                        0.01,  0.14,   6),
  ((SELECT id FROM f), '55',   'DLM/Rhod NP99',                       0.04,  0.36,   7),
  ((SELECT id FROM f), '56',   'SODA BICARB-Tata food grade',         0.20,  1.98,   8),
  ((SELECT id FROM f), '59',   'Microvit-C-35%/Rovimix Stay-C',       0.02,  0.20,   9),
  ((SELECT id FROM f), '60',   'Toxifin-360Dry(Kemin)',               0.13,  1.25,   10),
  ((SELECT id FROM f), '63',   'Phygest-10000-(Kemin)',               0.01,  0.10,   11),
  ((SELECT id FROM f), '77',   'Choline Chl-60%-(Jubliant/Balaji)',   0.13,  1.25,   12),
  ((SELECT id FROM f), '78',   'Kemzyme Protease-(Kemin)',            0.03,  0.25,   13),
  ((SELECT id FROM f), '82',   'Saf-Manans (Phileo)',                 0.03,  0.25,   14),
  ((SELECT id FROM f), '95',   'Breed Vitami-0.10%-Trow/DSM/Adiss',  0.10,  1.00,   15),
  ((SELECT id FROM f), '101',  'NEOLINC-Ravioza (L10+N10%)',          0.02,  0.20,   16),
  ((SELECT id FROM f), '163',  'AMINO-GABA-20% (CPBIO)',              0.03,  0.25,   17),
  ((SELECT id FROM f), '201',  'DCAD-Arm and Hammer',                 0.14,  1.36,   18),
  ((SELECT id FROM f), '238',  'Breeder In-TM-Avitech(Avimin)',       0.15,  1.50,   19),
  ((SELECT id FROM f), '301',  'Oregostim-1X-Saife-Vet',             0.03,  0.25,   20),
  ((SELECT id FROM f), '302',  'MCP-22%-Phos',                        0.98,  9.75,   21),
  ((SELECT id FROM f), '303',  'Shell Grit-36% Ca(Gaurika)',          3.55,  35.49,  22),
  ((SELECT id FROM f), '400',  '40 degree-Sunways',                   0.08,  0.75,   23),
  ((SELECT id FROM f), '0001', 'Kemtrace Supreme-Kemin',              0.08,  0.80,   24),
  ((SELECT id FROM f), '91.5', 'Vitamin-E-50%Rovimix',                0.02,  0.15,   25),
  ((SELECT id FROM f), '91.9', 'Buti Pearl(Kemin)',                   0.05,  0.50,   26),
  ((SELECT id FROM f), '92.5', 'Hepatocare(Versa)',                   0.05,  0.50,   27),
  ((SELECT id FROM f), '92.9', 'Endox-T Dry',                        0.02,  0.18,   28);

-- PL5-N ingredients (51st week to cullings)
WITH f AS (SELECT id FROM public.feed_formulas WHERE formula_code='PL5-N' LIMIT 1)
INSERT INTO public.feed_formula_ingredients (formula_id, ingredient_code, ingredient_name, percentage, kg_per_1000, sort_order) VALUES
  ((SELECT id FROM f), '11',   'MAIZE-12%Moisture',                   75.8,  758.22, 1),
  ((SELECT id FROM f), '15',   'RB OIl (5%FFA Max.)',                 0.26,  2.55,   2),
  ((SELECT id FROM f), '24',   'SOYA DOC-(46%CP)',                    13.5,  135.67, 3),
  ((SELECT id FROM f), '41',   'L SP-36.50%-Calcium-Gaurika',         4.00,  40.00,  4),
  ((SELECT id FROM f), '51',   'SALT-(Ankur)',                        0.23,  2.34,   5),
  ((SELECT id FROM f), '54',   'L-LYSINE-78%',                        0.01,  0.10,   6),
  ((SELECT id FROM f), '55',   'DLM/Rhod NP99',                       0.03,  0.28,   7),
  ((SELECT id FROM f), '56',   'SODA BICARB-Tata food grade',         0.24,  2.41,   8),
  ((SELECT id FROM f), '59',   'Microvit-C-35%/Rovimix Stay-C',       0.02,  0.20,   9),
  ((SELECT id FROM f), '60',   'Toxifin-360Dry(Kemin)',               0.13,  1.25,   10),
  ((SELECT id FROM f), '63',   'Phygest-10000-(Kemin)',               0.01,  0.10,   11),
  ((SELECT id FROM f), '77',   'Choline Chl-60%-(Jubliant/Balaji)',   0.13,  1.30,   12),
  ((SELECT id FROM f), '78',   'Kemzyme Protease-(Kemin)',            0.03,  0.25,   13),
  ((SELECT id FROM f), '82',   'Saf-Manans (Phileo)',                 0.03,  0.25,   14),
  ((SELECT id FROM f), '95',   'Breed Vitami-0.10%-Trow/DSM/Adiss',  0.10,  1.00,   15),
  ((SELECT id FROM f), '101',  'NEOLINC-Ravioza (L10+N10%)',          0.02,  0.20,   16),
  ((SELECT id FROM f), '163',  'AMINO-GABA-20% (CPBIO)',              0.03,  0.25,   17),
  ((SELECT id FROM f), '201',  'DCAD-Arm and Hammer',                 0.10,  1.04,   18),
  ((SELECT id FROM f), '238',  'Breeder In-TM-Avitech(Avimin)',       0.15,  1.50,   19),
  ((SELECT id FROM f), '301',  'Oregostim-1X-Saife-Vet',             0.03,  0.25,   20),
  ((SELECT id FROM f), '302',  'MCP-22%-Phos',                        0.94,  9.42,   21),
  ((SELECT id FROM f), '303',  'Shell Grit-36% Ca(Gaurika)',          3.85,  38.53,  22),
  ((SELECT id FROM f), '400',  '40 degree-Sunways',                   0.08,  0.75,   23),
  ((SELECT id FROM f), '0001', 'Kemtrace Supreme-Kemin',              0.08,  0.80,   24),
  ((SELECT id FROM f), '91.5', 'Vitamin-E-50%Rovimix',                0.02,  0.15,   25),
  ((SELECT id FROM f), '91.9', 'Buti Pearl(Kemin)',                   0.05,  0.50,   26),
  ((SELECT id FROM f), '92.5', 'Hepatocare(Versa)',                   0.05,  0.50,   27),
  ((SELECT id FROM f), '92.9', 'Endox-T Dry',                        0.02,  0.18,   28);

-- PL6-N ingredients (Male Feed)
WITH f AS (SELECT id FROM public.feed_formulas WHERE formula_code='PL6-N' LIMIT 1)
INSERT INTO public.feed_formula_ingredients (formula_id, ingredient_code, ingredient_name, percentage, kg_per_1000, sort_order) VALUES
  ((SELECT id FROM f), '11',   'MAIZE-12%Moisture',                   78.1,  781.81, 1),
  ((SELECT id FROM f), '24',   'SOYA DOC-(46%CP)',                    8.83,  88.33,  2),
  ((SELECT id FROM f), '31',   'DORB-17% Protein',                    6.78,  67.84,  3),
  ((SELECT id FROM f), '41',   'L SP-36.50%-Calcium-Gaurika',         4.00,  40.00,  4),
  ((SELECT id FROM f), '51',   'SALT-(Ankur)',                        0.23,  2.31,   5),
  ((SELECT id FROM f), '56',   'SODA BICARB-Tata food grade',         0.26,  2.56,   6),
  ((SELECT id FROM f), '59',   'Microvit-C-35%/Rovimix Stay-C',       0.02,  0.20,   7),
  ((SELECT id FROM f), '60',   'Toxifin-360Dry(Kemin)',               0.13,  1.25,   8),
  ((SELECT id FROM f), '63',   'Phygest-10000-(Kemin)',               0.01,  0.10,   9),
  ((SELECT id FROM f), '77',   'Choline Chl-60%-(Jubliant/Balaji)',   0.14,  1.37,   10),
  ((SELECT id FROM f), '78',   'Kemzyme Protease-(Kemin)',            0.03,  0.25,   11),
  ((SELECT id FROM f), '82',   'Saf-Manans (Phileo)',                 0.03,  0.25,   12),
  ((SELECT id FROM f), '95',   'Breed Vitami-0.10%-Trow/DSM/Adiss',  0.10,  1.00,   13),
  ((SELECT id FROM f), '101',  'NEOLINC-Ravioza (L10+N10%)',          0.02,  0.20,   14),
  ((SELECT id FROM f), '163',  'AMINO-GABA-20% (CPBIO)',              0.03,  0.25,   15),
  ((SELECT id FROM f), '201',  'DCAD-Arm and Hammer',                 0.04,  0.38,   16),
  ((SELECT id FROM f), '238',  'Breeder In-TM-Avitech(Avimin)',       0.10,  1.00,   17),
  ((SELECT id FROM f), '301',  'Oregostim-1X-Saife-Vet',             0.03,  0.25,   18),
  ((SELECT id FROM f), '302',  'MCP-22%-Phos',                        0.78,  7.83,   19),
  ((SELECT id FROM f), '400',  '40 degree-Sunways',                   0.08,  0.75,   20),
  ((SELECT id FROM f), '0001', 'Kemtrace Supreme-Kemin',              0.08,  0.75,   21),
  ((SELECT id FROM f), '91.5', 'Vitamin-E-50%Rovimix',                0.02,  0.15,   22),
  ((SELECT id FROM f), '91.9', 'Buti Pearl(Kemin)',                   0.05,  0.50,   23),
  ((SELECT id FROM f), '92.5', 'Hepatocare(Versa)',                   0.05,  0.50,   24),
  ((SELECT id FROM f), '92.9', 'Endox-T Dry',                        0.02,  0.18,   25);

-- ── Seed Vaccination Schedule (Narendra Breeder — 67 entries) ────
INSERT INTO public.vaccination_schedule (schedule_name, sno, age_label, vaccine_name, dose, route, product) VALUES
  ('Narendra Breeder', 1,  'Day 1',       'PREVEXXION MAREK''S LIVE',            '0.2 ML',                          'S/C',  'Boehringer'),
  ('Narendra Breeder', 2,  'Day 1',       'IB MA-5 Live AND IB 4/91',            '0.03 ML Each',                    'I/O',  'MSD'),
  ('Narendra Breeder', 3,  'Day 1 to 3',  'TILMICOSIN',                          '20mg/kg Bw (4.0 ml/1000 chicks)', 'D/W',  'SUNWAYS'),
  ('Narendra Breeder', 4,  '1-5 Days',    'LEVOZITHRO-BH',                       '15 MG/KG B W',                    'D/W',  'RAVIOZA'),
  ('Narendra Breeder', 5,  'Day 6',       'ND CLONE-30',                         '0.03 ML',                         'I/O',  'MSD'),
  ('Narendra Breeder', 6,  'Day 7',       'IBH KILLED',                          '0.3 ML',                          'S/C',  'VENTRI'),
  ('Narendra Breeder', 7,  'Day 7',       'PNEUMO VIRUS',                        '0.03 ML',                         'N/D',  'HIPRA'),
  ('Narendra Breeder', 8,  'Day 8',       'VVND KILLED (LP) (VENGEM-9)',         '0.3 ML',                          'I/M',  'VENTRI'),
  ('Narendra Breeder', 9,  'Day 10',      'ND+IBD KILLED',                       '0.3 ML',                          'S/C',  'VENTRI'),
  ('Narendra Breeder', 10, 'Day 10',      'IBD LIVE INTERMEDIATE TYPE',          '0.03 ML',                         'I/O',  'VENTRI'),
  ('Narendra Breeder', 11, 'Day 12',      'REO (LIVE)',                          '0.2 ML',                          'I/M',  'MSD'),
  ('Narendra Breeder', 12, 'Day 14',      'VVND KILLED (HP) New Strain',         '0.3 ML',                          'I/M',  'HESTER'),
  ('Narendra Breeder', 13, 'Day 20',      'IBD INTERMEDIATE (PLUS)',             '0.03 ML',                         'I/O',  'VENTRI'),
  ('Narendra Breeder', 14, 'Day 25',      'ILT (TISSUE CULTURE)',                '0.03 ML',                         'I/O',  'MSD'),
  ('Narendra Breeder', 15, 'Day 29',      'TILMICOSIN',                          '20mg/kg BW (45ML/1000 chicks) 3 days', 'D/W', 'SUNWAYS'),
  ('Narendra Breeder', 16, 'Day 33',      'IBMA-5 + ND CLONE-30 LIVE',          '1.5 DOSE',                        'D/W',  'MSD'),
  ('Narendra Breeder', 17, 'Day 35',      'Vectormune FP-MG',                   '0.01 ML',                         'W/W',  'Ceva'),
  ('Narendra Breeder', 18, 'Week 6',      'NOBILIS SG 9R',                      '0.2 ML',                          'S/C',  'MSD'),
  ('Narendra Breeder', 19, 'Week 7',      'CORYZA KILLED',                      '0.5 ML',                          'I/M',  'Boehringer'),
  ('Narendra Breeder', 20, 'Week 7',      'ND VISA-15',                         '0.5 ML',                          'I/M',  'VENTRI'),
  ('Narendra Breeder', 21, 'Week 8',      'AviPro Thymovac (Live)',             '1.0 Dose',                        'D/W',  'AviPro'),
  ('Narendra Breeder', 22, 'Week 8',      'PNEUMO VIRUS',                       '0.03 ML',                         'N/D',  'HIPRA/MSD'),
  ('Narendra Breeder', 23, 'Week 8',      'VVND KILLED (LP) (VENGEM-9)',        '0.5 ML',                          'I/M',  'VENTRI'),
  ('Narendra Breeder', 24, 'Week 8',      'IBH KILLED',                         '0.5 ML',                          'I/M',  'VENTRI'),
  ('Narendra Breeder', 25, 'Week 9',      'I Bird',                             '0.03 ML',                         'I/O',  'Ceva'),
  ('Narendra Breeder', 26, 'Week 9',      'REO KILLED',                         '0.5 ML',                          'I/M',  'MSD'),
  ('Narendra Breeder', 27, 'Week 10',     'R2B (LIVE)',                         '0.5 ML',                          'I/M',  'VENTRI'),
  ('Narendra Breeder', 28, 'Week 11',     'VVND KILLED (HP) New Strain',        '0.5 ML',                          'S/C',  'HESTER'),
  ('Narendra Breeder', 29, 'Week 11',     'ILT (CHICK EMBRYO)',                 '0.03 ML',                         'I/O',  'MSD'),
  ('Narendra Breeder', 30, 'Week 12',     'AE + FP',                            '0.01 ML',                         'W/W',  'MSD'),
  ('Narendra Breeder', 31, 'Week 12',     'IBV LIVE (MASS)',                    '1.5 Dose',                        'D/W',  'VENTRI'),
  ('Narendra Breeder', 32, 'Week 13',     'CORYZA KILLED',                      '0.5 ML',                          'I/M',  'Boehringer'),
  ('Narendra Breeder', 33, 'Week 13',     'ND VISA-15',                         '0.5 ML',                          'I/M',  'VENTRI'),
  ('Narendra Breeder', 34, 'Week 14',     'FC KILLED',                          '0.5 ML',                          'I/M',  'INDOVAX'),
  ('Narendra Breeder', 35, 'Week 14',     'ORT Killed',                         '0.5 ML',                          'I/M',  'VENTRI'),
  ('Narendra Breeder', 36, 'Week 15',     'MEGAMUNE-K',                         '0.5 ML',                          'I/M',  'Ceva'),
  ('Narendra Breeder', 37, 'Week 15',     'Salmonella Screening of 500 Birds',  NULL,                              NULL,   NULL),
  ('Narendra Breeder', 38, 'Week 15',     'SALMONELLA',                         '0.3 ML',                          'S/C',  'HIPRA/Boeh'),
  ('Narendra Breeder', 39, 'Week 16',     'I Bird Live',                        '0.03 ml',                         'I/O',  'Ceva'),
  ('Narendra Breeder', 40, 'Week 16',     'IBH KILLED',                         '0.5 ML',                          'I/M',  'Vaksindo'),
  ('Narendra Breeder', 41, 'Week 16',     'REO KILLED',                         '0.5 ML',                          'I/M',  'MSD'),
  ('Narendra Breeder', 42, 'Week 16',     'CAV KILLED (Optional)',              '0.5 ML',                          'I/M',  'VENTRI'),
  ('Narendra Breeder', 43, 'Week 17',     'ND Lasota Live',                     '1.5 Dose',                        'D/W',  'VENTRI'),
  ('Narendra Breeder', 44, 'Week 17',     'VVND KILLED (HP) New Strain',        '0.5 ML',                          'I/M',  'HESTER'),
  ('Narendra Breeder', 45, 'Week 17',     'IB-ASTRO (K) ONLY FEMALES',         '0.5 ML',                          'I/M',  'VENTRI'),
  ('Narendra Breeder', 46, 'Week 17',     'PNEUMO VIRUS',                       '0.03 ML',                         'N/D',  'HIPRA/MSD'),
  ('Narendra Breeder', 47, 'Week 18',     'IBV LIVE (MASS)',                    '1.5 DOSE',                        'D/W',  'VENTRI'),
  ('Narendra Breeder', 48, 'Week 18',     'PNEUMO KILLED',                      '0.5 ML',                          'I/M',  'GLOBION'),
  ('Narendra Breeder', 49, 'Week 18',     'Tylvalosin (SUNLOSIN 62.5%)',        '15MG/KG B/W x 3 days',           'D/W',  'SUNWAYS'),
  ('Narendra Breeder', 50, 'Week 19',     'VVND KILLED (LP) (VENGEM-9)',        '0.5 ML',                          'I/M',  'VENTRI'),
  ('Narendra Breeder', 51, 'Week 19',     'FC KILLED',                          '0.5 ML',                          'I/M',  'INDOVAX'),
  ('Narendra Breeder', 52, 'Week 20',     'AE + IBH Combined Killed',           '0.5 ML',                          'I/M',  'VENTRI'),
  ('Narendra Breeder', 53, 'Week 20',     'ORT Killed',                         '0.5 ML',                          'I/M',  'VENTRI'),
  ('Narendra Breeder', 54, 'Week 21',     'ND+IB+IBD+REO (4WAY)',              '0.5 ML',                          'I/M',  'VENTRI'),
  ('Narendra Breeder', 55, 'Week 21',     'EDS Killed',                         '0.5 ML',                          'I/M',  'VENTRI/Hester'),
  ('Narendra Breeder', 56, 'Week 21 (3rd)','Tylvalosin (SUNLOSIN 62.5%)',      '20MG/KG B/W x 3 days',           'D/W',  'SUNWAYS'),
  ('Narendra Breeder', 57, 'Week 22',     'IB-ASTRO (K) ONLY FEMALES',         '0.5 ML',                          'I/M',  'VENTRI'),
  ('Narendra Breeder', 58, 'Week 22',     'ND Lasota + IBV H120 Live',         '1.5 Dose',                        'D/W',  'VENTRI'),
  ('Narendra Breeder', 59, 'Week 26',     'ND Lasota Live',                     'Double Dose',                     'D/W',  'VENTRI'),
  ('Narendra Breeder', 60, 'Week 28',     'IB MA-5 Live',                       '1.5 Dose',                       'D/W',  'MSD'),
  ('Narendra Breeder', 61, 'Week 37',     'IBH KILLED',                         '0.5 ML',                          'I/M',  'Globion'),
  ('Narendra Breeder', 62, 'Week 38',     'ND VISA-15',                         '0.5 ML',                          'I/M',  'VENTRI'),
  ('Narendra Breeder', 63, 'Week 40',     'IB-ASTRO (K) ONLY FEMALES',         '0.5 ML',                          'I/M',  'VENTRI'),
  ('Narendra Breeder', 64, 'Week 42',     'ND+IB+IBD+REO (4WAY)',              '0.5 ML',                          'I/M',  'VENTRI'),
  ('Narendra Breeder', 65, 'Week 43',     'VVND KILLED (LP) (VENGEM-9)',        '0.5 ML',                          'I/M',  'VENTRI'),
  ('Narendra Breeder', 66, 'Week 44',     'VVND KILLED (HP) New Strain',        '0.5 ML',                          'I/M',  'HESTER'),
  ('Narendra Breeder', 67, 'Week 54',     'IBH KILLED',                         '0.5 ML',                          'I/M',  'Globion')
ON CONFLICT DO NOTHING;
