-- Migration: import 413 historical expense rows (Mandal + Head Office imprest,
-- confirmed by owner) into farm_expenses, and post each to cash_book so the
-- imprest float actually reflects the spend. Vehicle rows (no farm_code) post
-- against Head Office's float, confirmed by owner.

WITH v(expense_date, farm_code, category, description, vendor, amount, remarks) AS (VALUES
  ('2026-04-02'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-04-03'::date, 'BPET1', 'other', 'Being Amount Paid For Purchase a SS Nut Bolts For Site Usage', NULL, 80.0::numeric, NULL),
  ('2026-04-03'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally DG & Tractor Usage', NULL, 25000.0::numeric, NULL),
  ('2026-04-03'::date, 'BPET1', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet1 DG Usage', NULL, 25000.0::numeric, NULL),
  ('2026-04-03'::date, 'BPET2', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet2 DG USage', NULL, 10000.0::numeric, NULL),
  ('2026-04-03'::date, 'FEEDMILL', 'transport', 'Being Amount Paid For Oil Transport Charges', NULL, 2714.0::numeric, NULL),
  ('2026-04-05'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-04-08'::date, 'BPET1', 'other', 'Being Amount Paid For Purchase a Colin For Bpet1 Office Usage', NULL, 110.0::numeric, NULL),
  ('2026-04-08'::date, 'BPET1', 'other', 'Being Amount Paid For Purchase a Nut & Bolt For Bpet1 Site USage', NULL, 40.0::numeric, NULL),
  ('2026-04-08'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-04-12'::date, 'PPALLY', 'transport', 'Being Amount Paid  For Rewinding Motors Transport  Charges From Shamshabad To Site', NULL, 1613.0::numeric, NULL),
  ('2026-04-12'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-04-12'::date, 'BPET1', 'medical', 'Being Amount Paid To Tagari Majhi Medical Expences', NULL, 930.0::numeric, NULL),
  ('2026-04-13'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally DG & Tractor Usage', NULL, 25000.0::numeric, NULL),
  ('2026-04-13'::date, 'BPET1', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet1 DG Usage', NULL, 25000.0::numeric, NULL),
  ('2026-04-13'::date, 'BPET2', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet2 DG USage', NULL, 10000.0::numeric, NULL),
  ('2026-04-14'::date, '', 'fuel', 'Being Amount Paid For Creta Perol Expences', 'Creta', 4000.0::numeric, NULL),
  ('2026-04-14'::date, '', 'transport', 'Being Amount Paid For Creta Tollgate Expences', 'Creta', 1000.0::numeric, NULL),
  ('2026-04-14'::date, 'PPALLY', 'medical', 'Being Amount Paid To Lakeshwar Jagat Medical Expences', NULL, 570.0::numeric, NULL),
  ('2026-04-14'::date, 'BPET1', 'other', 'Being Amount Paid For Bpet1 3 HP Motor Rewinding Work Charges', NULL, 7800.0::numeric, NULL),
  ('2026-04-16'::date, 'BPET1', 'other', 'Being Amount Paid For Purchase a Water Taps & Cealing Fans Capacitors For Site Usage', NULL, 950.0::numeric, NULL),
  ('2026-04-16'::date, 'FEEDMILL', 'other', 'Being Amount Paid For  Sanjib Mondal Mobile Recharge Charges For 84 Days', NULL, 799.0::numeric, NULL),
  ('2026-04-19'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-04-19'::date, 'BPET1', 'maintenance', 'Being Amount Paid For Purchase a Castrol Engine Oil For Bpet1 Bike Usage', NULL, 500.0::numeric, NULL),
  ('2026-04-19'::date, 'BPET1', 'medical', 'Being Amount Paid To Tagari Majhi Medical Expences', NULL, 1000.0::numeric, NULL),
  ('2026-04-20'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-04-22'::date, 'BPET1', 'medical', 'Being Amount Paid To Tagari Majhi Medical Expences', NULL, 800.0::numeric, NULL),
  ('2026-04-23'::date, 'BPET1', 'other', 'Being Amount Paid For Bpet1 Cealing Fan Repair Charges', NULL, 580.0::numeric, NULL),
  ('2026-04-24'::date, 'PPALLY', 'other', 'Being Amount Paid For Management Fooding Charges', NULL, 4094.0::numeric, NULL),
  ('2026-04-26'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally DG & Tractor Usage', NULL, 25000.0::numeric, NULL),
  ('2026-04-26'::date, 'BPET1', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet1 DG Usage', NULL, 25000.0::numeric, NULL),
  ('2026-04-26'::date, 'BPET2', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet2 DG USage', NULL, 10000.0::numeric, NULL),
  ('2026-04-26'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally DG & Tractor Usage', NULL, 1623.0::numeric, NULL),
  ('2026-04-28'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-04-28'::date, 'PPALLY', 'other', 'Being Amount Paid For purchase a Nut & Bolt For Ppally tractor Usage', NULL, 300.0::numeric, NULL),
  ('2026-04-28'::date, 'PPALLY', 'maintenance', 'Being Amount Paid For Ppally Bike Tube Replace & Service Charges', NULL, 350.0::numeric, NULL),
  ('2026-04-28'::date, 'BPET1', 'other', 'Being Amount Paid For Purchase a Buckets For Site Usage', NULL, 1200.0::numeric, NULL),
  ('2026-04-29'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally DG & Tractor Usage', NULL, 25000.0::numeric, NULL),
  ('2026-04-29'::date, 'BPET1', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet1 DG Usage', NULL, 25000.0::numeric, NULL),
  ('2026-04-29'::date, 'BPET2', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet2 DG USage', NULL, 10000.0::numeric, NULL),
  ('2026-04-29'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-04-29'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-04-30'::date, 'FEEDMILL', 'other', 'Being Amount Paid For Driver Food Expences', NULL, 1000.0::numeric, NULL),
  ('2026-05-02'::date, 'PPALLY', 'maintenance', 'Being Amount Paid For Dozer Tractor Service Charges', NULL, 3870.0::numeric, NULL),
  ('2026-05-02'::date, 'KPALLY', 'transport', 'Being Amount Paid For Disel Brooders Transport Charges From Hyd To Kpally Site Usage', NULL, 5500.0::numeric, NULL),
  ('2026-05-03'::date, 'PPALLY', 'other', 'Being Amount Paid For Electricity Agreement Xerox Charges', NULL, 45.0::numeric, NULL),
  ('2026-05-04'::date, 'KPALLY', 'other', 'Being Amount Paid For Purchase a PVC Elbow & GI Wire For Kpally Site usage', NULL, 645.0::numeric, NULL),
  ('2026-05-04'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-05-04'::date, 'PPALLY', 'other', 'Being Amount Paid For Management Fooding Charges', NULL, 4450.0::numeric, NULL),
  ('2026-05-04'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-05-04'::date, 'PPALLY', 'other', 'Being Amount Paid For Purchase a 16A Switch & Coil For Ppally Site Usage', NULL, 1610.0::numeric, NULL),
  ('2026-05-04'::date, 'KPALLY', 'other', 'Being Amount Paid For Purchase a Jaggery 50Kg For Kpally New Flock Usage', NULL, 3000.0::numeric, NULL),
  ('2026-05-05'::date, 'PPALLY', 'other', 'Being Amount Paid For Electricity Agreement  Charges', NULL, 10000.0::numeric, NULL),
  ('2026-05-05'::date, 'PPALLY', 'maintenance', 'Being Amount Paid For Water Tanker Tyre Punchure Charges', NULL, 250.0::numeric, NULL),
  ('2026-05-06'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-05-06'::date, 'PPALLY', 'maintenance', 'Being Amount Paid For Ppally Bike Tyre Punchure Charges', NULL, 70.0::numeric, NULL),
  ('2026-05-06'::date, 'KPALLY', 'other', 'Being Amount Paid For Kpally Workers Food Expences', NULL, 3060.0::numeric, NULL),
  ('2026-05-06'::date, 'PPALLY', 'transport', 'Being Amount Paid For Sutili & Tape Box Transport Charges', NULL, 2580.0::numeric, NULL),
  ('2026-05-06'::date, 'PPALLY', 'transport', 'Being Amount Paid For H2O2 , Phenyol , Bleaching Powder Transport Charges', NULL, 4200.0::numeric, NULL),
  ('2026-05-07'::date, 'KPALLY', 'other', 'Being Amount Paid For Kpally Puja Charges', NULL, 500.0::numeric, NULL),
  ('2026-05-09'::date, '', 'fuel', 'Being Amount Paid For Creta Perol Expences', 'Creta', 3500.0::numeric, NULL),
  ('2026-05-09'::date, 'KPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Kpally DG Usage', NULL, 5000.0::numeric, NULL),
  ('2026-05-09'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-05-09'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally DG & Tractor Usage', NULL, 25000.0::numeric, NULL),
  ('2026-05-09'::date, 'BPET1', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet1 DG Usage', NULL, 25000.0::numeric, NULL),
  ('2026-05-09'::date, 'BPET2', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet2 DG USage', NULL, 10000.0::numeric, NULL),
  ('2026-05-09'::date, 'KPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Kpally DG Usage', NULL, 10000.0::numeric, NULL),
  ('2026-05-09'::date, '', 'fuel', 'Being Amount Paid For Creta Perol Expences', 'Creta', 4000.0::numeric, NULL),
  ('2026-05-11'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-05-11'::date, 'KPALLY', 'other', 'Being Amount Paid For Purchase a 50mm PVC Coupling For Kpally Site Usage', NULL, 170.0::numeric, NULL),
  ('2026-05-11'::date, 'PPALLY', 'other', 'Being Amount Paid For Purchase a 50mm PVC FTA/Reducer For Ppally Site Usage', NULL, 170.0::numeric, NULL),
  ('2026-05-12'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-05-12'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally DG & Tractor Usage', NULL, 25000.0::numeric, NULL),
  ('2026-05-12'::date, 'BPET1', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet1 DG Usage', NULL, 25000.0::numeric, NULL),
  ('2026-05-12'::date, 'BPET2', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet2 DG USage', NULL, 10000.0::numeric, NULL),
  ('2026-05-12'::date, 'KPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Kpally DG Usage', NULL, 10000.0::numeric, NULL),
  ('2026-05-13'::date, 'PPALLY', 'other', 'Being Amount Paid For Purchase a Coolent Oil 10 Ltrs For Ppally Site DG Usage', NULL, 2100.0::numeric, NULL),
  ('2026-05-13'::date, 'PPALLY', 'other', 'Being Amount Paid For Ppally Site Cealing Fan''s Rewinding Charges', NULL, 2250.0::numeric, NULL),
  ('2026-05-13'::date, 'BPET1', 'other', 'Being Amount Paid For Bpet1 DG Lifting Charges', NULL, 2700.0::numeric, NULL),
  ('2026-05-14'::date, 'FEEDMILL', 'other', 'Being Amount Paid For Extra Labour Expences For Feedmill', NULL, 3800.0::numeric, NULL),
  ('2026-05-17'::date, 'FEEDMILL', 'other', 'Being Amount Paid For Purchase a Gate Wall , Coupling , Liquid Gum For Feedmill Site Usage', NULL, 240.0::numeric, NULL),
  ('2026-05-18'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-05-18'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-05-19'::date, 'KPALLY', 'other', 'Being Amount Paid For Purchase a Cealing Fan nut & Bolts For Kpally Site Usage', NULL, 150.0::numeric, NULL),
  ('2026-05-19'::date, 'KPALLY', 'other', 'Being Amount Paid For Purchase a BEC Relay For Kpally Site Usage', NULL, 400.0::numeric, NULL),
  ('2026-05-19'::date, 'KPALLY', 'other', 'Being Amount Paid For Kpally  Bore Motor Lifting Charges', NULL, 2500.0::numeric, NULL),
  ('2026-05-20'::date, 'PPALLY', 'maintenance', 'Being Amount Paid For Ppally Bike Tyre Tube Charges', NULL, 350.0::numeric, NULL),
  ('2026-05-21'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-05-21'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally DG & Tractor Usage', NULL, 5000.0::numeric, NULL),
  ('2026-05-22'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally DG & Tractor Usage', NULL, 25000.0::numeric, NULL),
  ('2026-05-22'::date, 'BPET1', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet1 DG Usage', NULL, 25000.0::numeric, NULL),
  ('2026-05-22'::date, 'BPET2', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet2 DG USage', NULL, 10000.0::numeric, NULL),
  ('2026-05-22'::date, 'KPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Kpally DG Usage', NULL, 10000.0::numeric, NULL),
  ('2026-05-23'::date, 'FEEDMILL', 'other', 'Being Amount Paid For Purchase a Knife For Feedmill Usage', NULL, 100.0::numeric, NULL),
  ('2026-05-24'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally DG & Tractor Usage', NULL, 25000.0::numeric, NULL),
  ('2026-05-24'::date, 'BPET1', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet1 DG Usage', NULL, 25000.0::numeric, NULL),
  ('2026-05-24'::date, 'BPET2', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet2 DG USage', NULL, 10000.0::numeric, NULL),
  ('2026-05-24'::date, 'KPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Kpally DG Usage', NULL, 10000.0::numeric, NULL),
  ('2026-05-25'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-05-25'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-05-28'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-05-30'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-06-01'::date, 'FEEDMILL', 'other', 'Being Amount Paid For Driver Food Expences', NULL, 700.0::numeric, NULL),
  ('2026-06-03'::date, 'PPALLY', 'other', 'Being Amount Paid For Cull Birds Balance Amount Ref No : 0090', NULL, 1000.0::numeric, NULL),
  ('2026-06-03'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-06-04'::date, '', 'fuel', 'Being Amount Paid For Creta Perol Expences', 'Creta', 4605.0::numeric, NULL),
  ('2026-06-06'::date, 'PPALLY', 'other', 'Being Amount Paid For Advance For Purchase Of Fire Wood', NULL, 2500.0::numeric, NULL),
  ('2026-06-07'::date, 'BPET1', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet1 DG Usage', NULL, 5000.0::numeric, NULL),
  ('2026-06-09'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-06-09'::date, 'BPET1', 'maintenance', 'Being Amount Paid For Bpet1 Bike Punchure Charges', NULL, 80.0::numeric, NULL),
  ('2026-06-09'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-06-10'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally Tractor Usage', NULL, 5000.0::numeric, NULL),
  ('2026-06-10'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-06-12'::date, 'PPALLY', 'transport', 'Being Amount Paid  For Medicine Transport  Charges From Hyderabad To Site', NULL, 2366.0::numeric, NULL),
  ('2026-06-13'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-06-13'::date, 'KPALLY', 'other', 'Being Amount Paid For Purchase a Knife For Site Usage', NULL, 220.0::numeric, NULL),
  ('2026-06-13'::date, 'BPET1', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet1 DG Usage', NULL, 25000.0::numeric, NULL),
  ('2026-06-14'::date, 'BPET1', 'other', 'Being Amount Paid For Electrical line Man Charges', NULL, 1000.0::numeric, NULL),
  ('2026-06-14'::date, 'KPALLY', 'other', 'Being Amount Paid For Purchase a Plumbing Saman', NULL, 300.0::numeric, NULL),
  ('2026-06-17'::date, 'BPET1', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet1 DG Usage', NULL, 15000.0::numeric, NULL),
  ('2026-06-17'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-06-19'::date, 'KPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Kpally DG Usage', NULL, 5000.0::numeric, NULL),
  ('2026-06-19'::date, 'KPALLY', 'other', 'Being Amount Paid For Purchase a PVC Saman For Site Usage', NULL, 250.0::numeric, NULL),
  ('2026-06-19'::date, 'PPALLY', 'other', 'Being Amount Paid For Management Fooding Charges', NULL, 800.0::numeric, NULL),
  ('2026-06-21'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-06-21'::date, 'KPALLY', 'other', 'Being Amount Paid For Purchase a GI Wire 5Kg For Site Usage', NULL, 550.0::numeric, NULL),
  ('2026-06-21'::date, 'BPET1', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet1 DG Usage', NULL, 5000.0::numeric, NULL),
  ('2026-06-22'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally Tractor Usage', NULL, 5000.0::numeric, NULL),
  ('2026-06-22'::date, 'PPALLY', 'maintenance', 'Being Amount Paid For Ppally Bike Tube & Tyre Fitting Charges', NULL, 370.0::numeric, NULL),
  ('2026-06-23'::date, 'BPET1', 'other', 'Being Amount Paid For Purchase a Sand Paper For Site Usage', NULL, 550.0::numeric, NULL),
  ('2026-06-24'::date, 'KPALLY', 'other', 'Being Amount Paid For Purchase a Plumbing Saman For Site Usage', NULL, 300.0::numeric, NULL),
  ('2026-06-24'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-06-24'::date, '', 'transport', 'Being Amount Paid For Creta Tollgate Expences', 'Creta', 1000.0::numeric, NULL),
  ('2026-06-25'::date, 'PPALLY', 'other', 'Being Amount Paid For Purchase a Cement Bags 6 Nos For Site Usage', NULL, 1850.0::numeric, NULL),
  ('2026-06-25'::date, 'BPET2', 'other', 'Being Amount Paid For Purchase a Cement Bags 6 Nos For Site Usage', NULL, 1850.0::numeric, NULL),
  ('2026-06-25'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-06-27'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally Tractor Usage', NULL, 5000.0::numeric, NULL),
  ('2026-06-29'::date, 'BPET1', 'maintenance', 'Being Amount Paid For Bpet1 Bolero Oil Filter Expences', NULL, 230.0::numeric, NULL),
  ('2026-06-29'::date, 'PPALLY', 'other', 'Being Amount Paid For Purchase a Brush , Tarpalin Oil & Colour  For Site Usage', NULL, 275.0::numeric, NULL),
  ('2026-06-29'::date, 'BPET2', 'other', 'Being Amount Paid For Purchase a Brush , Tarpalin Oil & Colour  For Site Usage', NULL, 275.0::numeric, NULL),
  ('2026-06-29'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-06-30'::date, '', 'fuel', 'Being Amount Paid For Creta Perol Expences', 'Creta', 4000.0::numeric, NULL),
  ('2026-06-30'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-06-30'::date, 'PPALLY', 'medical', 'Being Amount Paid To Raja Mohanta Medical Expences', NULL, 570.0::numeric, NULL),
  ('2026-07-04'::date, 'BPET1', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet1 DG Usage', NULL, 5216.0::numeric, NULL),
  ('2026-07-04'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally Tractor Usage', NULL, 5000.0::numeric, NULL),
  ('2026-07-05'::date, 'BPET2', 'other', 'Being Amount Paid For Purchase a Washing Machine Bearing', NULL, 600.0::numeric, NULL),
  ('2026-07-05'::date, 'PPALLY', 'other', 'Being Amount Paid For Purchase a Iron Items For Site Usage', NULL, 6110.0::numeric, NULL),
  ('2026-07-07'::date, 'PPALLY', 'transport', 'Being Amount Paid  For Medicine Transport  Charges', NULL, 350.0::numeric, NULL),
  ('2026-07-07'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-07-07'::date, 'PPALLY', 'maintenance', 'Being Amount Paid For Feed Tractor Self Motor Repair Charges', NULL, 1850.0::numeric, NULL),
  ('2026-07-08'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-07-08'::date, 'KPALLY', 'other', 'Being Amount Paid For Purchase a Plumbing Saman For Site Usage', NULL, 280.0::numeric, NULL),
  ('2026-07-08'::date, 'PPALLY', 'other', 'Being Amount Paid For Purchase a Cement Bags 15 Nos For Site Usage', NULL, 4575.0::numeric, NULL),
  ('2026-07-08'::date, 'BPET2', 'other', 'Being Amount Paid For Purchase a Cement Bags 15 Nos For Site Usage', NULL, 4575.0::numeric, NULL),
  ('2026-07-09'::date, 'BPET1', 'maintenance', 'Being Amount Paid For Bpet1 Bolero Service Expences', NULL, 4090.0::numeric, NULL),
  ('2026-07-10'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally Tractor Usage', NULL, 5000.0::numeric, NULL),
  ('2026-07-10'::date, 'FEEDMILL', 'other', 'Being Amount Paid For  Sanjib Mondal Mobile Recharge Charges For 84 Days', NULL, 799.0::numeric, NULL),
  ('2026-07-10'::date, 'BPET1', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet1 DG Usage', NULL, 5000.0::numeric, NULL),
  ('2026-07-11'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-07-12'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally Tractor Usage', NULL, 5000.0::numeric, NULL),
  ('2026-07-13'::date, 'BPET1', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet1 DG Usage', NULL, 5000.0::numeric, NULL),
  ('2026-07-13'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-07-13'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-07-16'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-07-16'::date, 'PPALLY', 'other', 'Being Amount Paid For Purchase a Civil Saman For Site Usage', NULL, 240.0::numeric, NULL),
  ('2026-07-16'::date, 'PPALLY', 'other', 'Being Amount Paid For Ppally Incharge Fooding Charges', NULL, 270.0::numeric, NULL),
  ('2026-07-17'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-07-17'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally Tractor Usage', NULL, 5000.0::numeric, NULL),
  ('2026-07-17'::date, 'PPALLY', 'maintenance', 'Being Amount Paid For Dozer Tractor Punchure Charges', NULL, 150.0::numeric, NULL),
  ('2026-07-17'::date, 'PPALLY', 'maintenance', 'Being Amount Paid For Ashok Leyland Service Charges', NULL, 7900.0::numeric, NULL),
  ('2026-07-19'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally Tractor Usage', NULL, 5000.0::numeric, NULL),
  ('2026-07-20'::date, 'BPET1', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet1 DG Usage', NULL, 5000.0::numeric, NULL),
  ('2026-07-20'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-07-21'::date, 'BPET1', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet1 DG Usage', NULL, 5000.0::numeric, NULL),
  ('2026-07-21'::date, 'PPALLY', 'other', 'Being Amount Paid For Management Fooding Charges', NULL, 1075.0::numeric, NULL),
  ('2026-07-22'::date, 'BPET1', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet1 DG Usage', NULL, 5000.0::numeric, NULL),
  ('2026-07-22'::date, 'PPALLY', 'transport', 'Being Amount Paid  For Medicine Transport  Charges From Hyderabad To Site', NULL, 2225.0::numeric, NULL),
  ('2026-07-23'::date, 'KPALLY', 'medical', 'Being Amount Paid To Lakeshwar Jagat Medical Expences', NULL, 550.0::numeric, NULL),
  ('2026-07-23'::date, '', 'fuel', 'Being Amount Paid For Creta Perol Expences', 'Creta', 10545.0::numeric, NULL),
  ('2026-07-23'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-07-24'::date, 'BPET1', 'other', 'Being Amount Paid For Battery Teriminals ', NULL, 360.0::numeric, NULL),
  ('2026-07-24'::date, 'PPALLY', 'other', 'Being Amount Paid For SBI Bank Staff Fooding Charges', NULL, 1080.0::numeric, NULL),
  ('2026-07-24'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-07-24'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally Tractor Usage', NULL, 5000.0::numeric, NULL),
  ('2026-07-25'::date, 'KPALLY', 'other', 'Being Amount Paid For Purchase a GI Wire 12Kg For Site Usage', NULL, 1260.0::numeric, NULL),
  ('2026-07-25'::date, 'PPALLY', 'transport', 'Being Amount Paid  For Bleaching Powder & H2O2  Transport Charges From Hyderabad To Site', NULL, 2690.0::numeric, NULL),
  ('2026-07-26'::date, 'BPET1', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet1 DG Usage', NULL, 5000.0::numeric, NULL),
  ('2026-07-27'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-07-27'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-07-27'::date, 'PPALLY', 'other', 'Being Amount Paid For Pradip Patra Travelling Expences From Site To Hyd For Given To SBI Signature Documents', NULL, 300.0::numeric, NULL),
  ('2026-07-27'::date, 'KPALLY', 'other', 'Being Amount Paid For Purchase a Plumbing Saman For Site Usage', NULL, 1060.0::numeric, NULL),
  ('2026-07-27'::date, 'BPET1', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet1 DG Usage', NULL, 5000.0::numeric, NULL),
  ('2026-07-28'::date, 'BPET1', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet1 DG Usage', NULL, 5000.0::numeric, NULL),
  ('2026-07-30'::date, 'BPET1', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet1 DG Usage', NULL, 20000.0::numeric, NULL),
  ('2026-07-30'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally Tractor Usage', NULL, 5000.0::numeric, NULL),
  ('2026-07-30'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-07-30'::date, 'PPALLY', 'medical', 'Being Amount Paid To Suryakanta Behera Medical Expences', NULL, 2570.0::numeric, NULL),
  ('2026-08-02'::date, 'PPALLY', 'maintenance', 'Being Amount Paid For Purchase a Bolero Nut & Bolts', NULL, 60.0::numeric, NULL),
  ('2026-08-02'::date, 'BPET1', 'other', 'Being Amount Paid For Purchase a Stationary Itmes Bag  , Stappler & Stappler pins', NULL, 240.0::numeric, NULL),
  ('2026-08-04'::date, 'KPALLY', 'other', 'Being Amount Paid For Purchase a Electrical Wire 2.5 MM Wire 1 Bundle', NULL, 4150.0::numeric, NULL),
  ('2026-08-04'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-08-04'::date, 'FEEDMILL', 'transport', 'Being Amount Paid For Medicine Transport Charges', NULL, 4500.0::numeric, NULL),
  ('2026-08-04'::date, 'KPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Kpally DG Usage', NULL, 40000.0::numeric, NULL),
  ('2026-08-05'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-08-05'::date, 'KPALLY', 'fuel', 'Being Amount Paid For purchase a petrol For Brooding Time Fogging Purpose Usage F-23', NULL, 500.0::numeric, NULL),
  ('2026-08-06'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally Tractor Usage', NULL, 5000.0::numeric, NULL),
  ('2026-08-06'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-08-06'::date, 'KPALLY', 'other', 'Being Amount Paid For Purchase a Gas regulator Nozzle For Kpally Site Usage', NULL, 3080.0::numeric, NULL),
  ('2026-08-06'::date, '', 'fuel', 'Being Amount Paid For Creta Perol Expences', 'Creta', 5600.0::numeric, NULL),
  ('2026-08-06'::date, '', 'transport', 'Being Amount Paid For Creta Tollgate Expences', 'Creta', 1000.0::numeric, NULL),
  ('2026-08-06'::date, 'KPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Kpally DG Usage', NULL, 40000.0::numeric, NULL),
  ('2026-08-08'::date, 'KPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Kpally DG Usage', NULL, 40000.0::numeric, NULL),
  ('2026-08-08'::date, 'PPALLY', 'maintenance', 'Being Amount Paid For Purchase a Ppally Bike Spark Plug', NULL, 100.0::numeric, NULL),
  ('2026-08-10'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally Tractor Usage', NULL, 5000.0::numeric, NULL),
  ('2026-08-10'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-08-10'::date, 'PPALLY', 'other', 'Being Amount Paid For Purchase a Brush & Fan Capacitors', NULL, 2380.0::numeric, NULL),
  ('2026-08-11'::date, 'BPET2', 'other', 'Being Amount Paid For Bpet2 Cealing Fan Rewinding Charges', NULL, 430.0::numeric, NULL),
  ('2026-08-11'::date, 'BPET1', 'other', 'Being Amount Paid For Purchase a Sand Paper Box For Bpet1 Usage', NULL, 540.0::numeric, NULL),
  ('2026-08-11'::date, 'KPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Kpally DG Usage', NULL, 40000.0::numeric, NULL),
  ('2026-08-12'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-08-12'::date, 'KPALLY', 'medical', 'Being Amount Paid To Shilpa Mediya Medical Expences', NULL, 3674.0::numeric, NULL),
  ('2026-08-13'::date, 'PPALLY', 'maintenance', 'Being Amount Paid For Purchase a Ppally Ashokleyland Punchure & Fitting Charges', NULL, 130.0::numeric, NULL),
  ('2026-08-13'::date, '', 'fuel', 'Being Amount Paid For Creta Perol Expences', 'Creta', 4000.0::numeric, NULL),
  ('2026-08-13'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally Tractor Usage', NULL, 5000.0::numeric, NULL),
  ('2026-08-13'::date, 'BPET1', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet1 DG Usage', NULL, 5000.0::numeric, NULL),
  ('2026-08-17'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-08-17'::date, 'PPALLY', 'maintenance', 'Being Amount Paid For Purchase a  Ppally Bike Spark Plug', NULL, 100.0::numeric, NULL),
  ('2026-08-17'::date, 'PPALLY', 'other', 'Being Amount Paid For Independence Day Expences All Sites', NULL, 8290.0::numeric, NULL),
  ('2026-08-17'::date, 'PPALLY', 'transport', 'Being Amount Paid For Cage Mats Transport Charges', NULL, 39000.0::numeric, NULL),
  ('2026-08-18'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally Tractor Usage', NULL, 500.0::numeric, NULL),
  ('2026-08-18'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Ppally Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-08-18'::date, 'PPALLY', 'maintenance', 'Being Amount Paid For Purchase a  Nut & Bolt For Feed tractor Usage', NULL, 80.0::numeric, NULL),
  ('2026-08-18'::date, 'PPALLY', 'maintenance', 'Being Amount Paid For Feed Tractor Repair Charges', NULL, 23172.0::numeric, NULL),
  ('2026-08-19'::date, 'PPALLY', 'fuel', 'Being Amount Paid For Diesel Expences Of Ppally Tractor Usage', NULL, 5000.0::numeric, NULL),
  ('2026-08-19'::date, 'BPET1', 'fuel', 'Being Amount Paid For Bpet1 Bike Petrol Expences', NULL, 500.0::numeric, NULL),
  ('2026-08-19'::date, 'PPALLY', 'maintenance', 'Being Amount Paid For Punchure Charges Of Ppally Bike', NULL, 50.0::numeric, NULL),
  ('2026-08-19'::date, 'BPET1', 'fuel', 'Being Amount Paid For Diesel Expences Of Bpet1 DG Usage', NULL, 5000.0::numeric, NULL),
  ('2026-08-19'::date, 'PPALLY', 'transport', 'Being Amount Paid For Tarpaulin Transport Charges', NULL, 4252.0::numeric, NULL),
  ('2026-04-03'::date, '', 'fuel', 'Being Amount Paid For Innova Diesel Expences', 'Innova', 4470.0::numeric, 'Paid by DSR'),
  ('2026-04-04'::date, '', 'fuel', 'Being Amount Paid For Activa Petrol Expences', 'Activa', 490.0::numeric, 'Paid by DLR'),
  ('2026-04-05'::date, '', 'fuel', 'Being Amount Paid For Innova Diesel Expences', 'Innova', 4655.0::numeric, 'Paid by DNR'),
  ('2026-04-06'::date, 'HO', 'other', 'Being Amount Paid For Office Microsoft One Drive Monthly Charges', NULL, 619.0::numeric, 'Paid by DLR'),
  ('2026-04-06'::date, 'HO', 'other', 'Being Amount Paid For DSR JIo Yearly Recharge', NULL, 3599.0::numeric, 'Paid by DLR'),
  ('2026-04-06'::date, 'HO', 'other', 'Being Amount Paid For Office Tea Or Buttermilk Expences', NULL, 1200.0::numeric, 'Paid by DLR'),
  ('2026-04-08'::date, 'HO', 'other', 'Being Amount Paid For office Jio Internet Charges', NULL, 1061.0::numeric, 'Paid by DLR'),
  ('2026-04-09'::date, '', 'fuel', 'Being Amount Paid For Activa Petrol Expences', 'Activa', 490.0::numeric, 'Paid by DLR'),
  ('2026-04-10'::date, 'HO', 'other', 'Being Amount Paid For Purchase a POT For Office Drinking Water Usage', NULL, 400.0::numeric, 'Paid by DLR'),
  ('2026-04-11'::date, 'HO', 'other', 'Being Amount Paid For Purchase a 4 Port USB Hub For Office Usage', NULL, 500.0::numeric, 'Paid by DLR'),
  ('2026-04-12'::date, 'HO', 'other', 'Being Amount Paid For Purchase a Mouse For Office Usage', NULL, 1018.0::numeric, 'Paid by DLR'),
  ('2026-04-14'::date, 'HO', 'transport', 'Being Amount Paid For Rapido Charges From Secunderabad To Head Office', NULL, 250.0::numeric, 'Paid by DLR'),
  ('2026-04-14'::date, 'HO', 'other', 'Being Amount Paid For Office Electricity Charges For the Month Of March 26', NULL, 733.0::numeric, 'Paid by DLR'),
  ('2026-04-15'::date, '', 'other', 'Being Amount Paid For Ambdekar Statue Inaguration Donation Of Agraharam Potlapally Village', 'Site', 7500.0::numeric, 'Paid by DSR'),
  ('2026-04-15'::date, '', 'other', 'Being Amount Paid For Ambdekar Statue Inaguration Donation Of Agraharam Potlapally Village', 'Site', 7500.0::numeric, 'Paid by DSR'),
  ('2026-04-15'::date, 'HO', 'other', 'Being Amount Paid For Purchase Windows11 Activation Keys For Office New System Usage', NULL, 1332.0::numeric, 'Paid by DLR'),
  ('2026-04-15'::date, '', 'fuel', 'Being Amount Paid For Innova Petrol Expences', 'Innova', 4477.0::numeric, 'Paid by DSR'),
  ('2026-04-15'::date, 'HO', 'other', 'Being Amount Paid For Office Maid Charges For the Month Of April 26', NULL, 2500.0::numeric, 'Paid by DLR'),
  ('2026-04-15'::date, 'HO', 'other', 'Being Amount Paid For Office Apartment Monthly Mainteance Charges For thge Month of April 26', NULL, 3500.0::numeric, 'Paid by DLR'),
  ('2026-04-15'::date, '', 'transport', 'Being Amount Paid For Innova Tollgate Charges For The Month Of April 26', 'Innova', 3600.0::numeric, 'Paid by DLR'),
  ('2026-04-15'::date, 'HO', 'other', 'Being Amount Paid For Office Tea Or Buttermilk Expences', NULL, 1200.0::numeric, 'Paid by DLR'),
  ('2026-04-17'::date, '', 'maintenance', 'Being Amount Paid For Innova Car Head Light Bulb Replace & Service Charges', 'Innova', 700.0::numeric, 'Paid by DLR'),
  ('2026-04-18'::date, '', 'fuel', 'Being Amount Paid For Innova Petrol Expences', 'Innova', 4309.0::numeric, 'Paid by DSR'),
  ('2026-04-18'::date, '', 'fuel', 'Being Amount Paid For Activa Petrol Expences', 'Activa', 400.0::numeric, 'Paid by DLR'),
  ('2026-04-18'::date, '', 'fuel', 'Being Amount Paid For Innova Diesel Expences', 'Innova', 4522.0::numeric, 'Paid by DNR'),
  ('2026-04-20'::date, 'HO', 'other', 'Being Amount Paid For Purchase a Mobile For Head Office Usage', NULL, 17450.0::numeric, 'Paid by DNR'),
  ('2026-04-20'::date, 'HO', 'other', 'Being Amount Paid For Purchase a Stationery Items For OFfice Usage', NULL, 6429.0::numeric, 'Paid by DLR'),
  ('2026-04-20'::date, 'HO', 'other', 'Being Amount Paid For Purchase a Stationery Items For OFfice Usage', NULL, 6426.0::numeric, 'Paid by DLR'),
  ('2026-04-20'::date, '', 'other', 'Being Amount Paid For Site CC Camera Recharges For Two Months 09 Nos ,01 Camera One Month', 'Site', 5890.0::numeric, 'Paid by DLR'),
  ('2026-04-20'::date, 'HO', 'other', 'Being Amount Paid For Office Gmail Storage Monthly Charges', NULL, 108.0::numeric, 'Paid by DLR'),
  ('2026-04-21'::date, '', 'transport', 'Being Amount Paid For Dr.OP Singh Flight Ticket Charges', 'Site', 7592.0::numeric, 'Paid by DLR'),
  ('2026-04-23'::date, '', 'fuel', 'Being Amount Paid For Innova Petrol Expences', 'Innova', 4552.0::numeric, 'Paid by DSR'),
  ('2026-04-23'::date, 'HO', 'other', 'Being Amount Paid For Office Tea Or Buttermilk Expences', NULL, 1000.0::numeric, 'Paid by DLR'),
  ('2026-04-24'::date, '', 'fuel', 'Being Amount Paid For Activa Petrol Expences', 'Activa', 505.0::numeric, 'Paid by DLR'),
  ('2026-04-25'::date, '', 'fuel', 'Being Amount Paid For Innova Diesel Expences', 'Innova', 4295.0::numeric, 'Paid by DNR'),
  ('2026-04-25'::date, '', 'fuel', 'Being Amount Paid For Innova Diesel Expences', 'Innova', 3976.0::numeric, 'Paid by DSR'),
  ('2026-04-26'::date, '', 'fuel', 'Being Amount Paid For Innova Diesel Expences', 'Innova', 6750.0::numeric, 'Paid by DSR'),
  ('2026-04-27'::date, 'HO', 'other', 'Being Amount Paid For ACT Internet Advance Payment', NULL, 2828.0::numeric, 'Paid by DLR'),
  ('2026-04-27'::date, '', 'transport', 'Being Amount Paid For Dosth Ashokleyland Tollgate Recharge', 'Dosth-AshokLeyland', 500.0::numeric, 'Paid by DLR'),
  ('2026-04-28'::date, '', 'fuel', 'Being Amount Paid For Innova Diesel Expences', 'Innova', 3900.0::numeric, 'Paid by DNR'),
  ('2026-04-29'::date, '', 'fuel', 'Being Amount Paid For Activa Petrol Expences', 'Activa', 470.0::numeric, 'Paid by DLR'),
  ('2026-04-29'::date, '', 'other', 'Being Amount Paid For Site Manager Arjun Laptop Repair Charges', 'Site', 2000.0::numeric, 'Paid by DLR'),
  ('2026-04-30'::date, 'HO', 'other', 'Being Amount Paid For Drinking Water Charges                  12 Cans * 35/-', NULL, 420.0::numeric, 'Paid by DLR'),
  ('2026-04-30'::date, 'HO', 'transport', 'Being Amount Paid For Travelling Expences To Office Attender Venktaiah From Office To Injapur (VHPL) Unit For Submitting Bpet2 F-21  April 26 Invoice', NULL, 120.0::numeric, 'Paid by DLR'),
  ('2026-04-30'::date, 'HO', 'other', 'Being Amount Paid For Purchase a Electrical Hand Gloves For Site Usage', NULL, 3446.0::numeric, 'Paid by DLR'),
  ('2026-04-30'::date, 'HO', 'other', 'Being Amount Paid For Purchase a News Paper @124Kg @30/-  For New Flock 22 Usage', NULL, 3720.0::numeric, 'Paid by DLR'),
  ('2026-04-30'::date, 'HO', 'other', 'Being Amount Paid For Tally Renewal Charges For 1 Year', NULL, 15930.0::numeric, 'Paid by DNR'),
  ('2026-04-30'::date, '', 'maintenance', 'Being Amount Paid For Dosth Road Tax Renewal Charges', 'Dosth-AshokLeyland', 1160.0::numeric, 'Paid by DLR'),
  ('2026-04-30'::date, 'HO', 'transport', 'Being Amount Paid For Transport Charges From Diamond Farm Equipment To Office  For Vaccinators', NULL, 195.0::numeric, 'Paid by DLR'),
  ('2026-05-01'::date, '', 'fuel', 'Being Amount Paid For Innova Diesel Expences', 'Innova', 4150.0::numeric, 'Paid by DNR'),
  ('2026-05-02'::date, 'HO', 'transport', 'Being Amount Paid For Travelling Expences To Office Attender Venktaiah From Office To Balanagar to & Pro For Electricity Agrements taken to office From Site to Office', NULL, 270.0::numeric, 'Paid by DLR'),
  ('2026-05-05'::date, 'HO', 'other', 'Being Amount Paid For Office Microsoft One Drive Monthly Charges', NULL, 619.0::numeric, 'Paid by DLR'),
  ('2026-05-06'::date, '', 'fuel', 'Being Amount Paid For Innova Diesel Expences', 'Innova', 4443.0::numeric, 'Paid by DNR'),
  ('2026-05-06'::date, 'HO', 'other', 'Being Amount Paid For Office Electricity Charges For the Month Of April 26', NULL, 1792.0::numeric, 'Paid by DLR'),
  ('2026-05-06'::date, '', 'other', 'Being Amount Paid For Purchase a Electrical Cables For Site Usage', 'Site', 3761.0::numeric, 'Paid by DNR'),
  ('2026-05-07'::date, 'HO', 'other', 'Being Amount paid For office rental Agreement Frankling Charges For The Year FY 2026-27', NULL, 120.0::numeric, 'Paid by DLR'),
  ('2026-05-07'::date, '', 'other', 'Being Amount Paid For Purchase a Sponges For Site Usage', 'Site', 375.0::numeric, 'Paid by DNR'),
  ('2026-05-07'::date, '', 'fuel', 'Being Amount Paid For Activa Petrol Expences', 'Activa', 476.0::numeric, 'Paid by DLR'),
  ('2026-05-07'::date, '', 'other', 'Being Amount Paid For Purchase a 2.5 MFD Cealing Fan Capacitors For Site Usage', 'Site', 440.0::numeric, 'Paid by DNR'),
  ('2026-05-07'::date, '', 'other', 'Being Amount Paid For Purchase a Electrical Sockets & Switches For Site Usage', 'Site', 350.0::numeric, 'Paid by DLR'),
  ('2026-05-07'::date, '', 'other', 'Being Amount paid For Purchase a Broom Sticks 300 Nos For Site Usage', 'Site', 5100.0::numeric, 'Paid by DNR'),
  ('2026-05-07'::date, 'HO', 'transport', 'Being Amount Paid For Broom Sticks Rapido Transport Charges From Abzal Gunz to Office', NULL, 200.0::numeric, 'Paid by DLR'),
  ('2026-05-08'::date, '', 'other', 'Being Amount Paid For Purchase a Electrical Industrial Plug 3 in one Female Piece 6 Nos For Site Usage', 'Site', 3161.0::numeric, 'Paid by DLR'),
  ('2026-05-08'::date, '', 'transport', 'Being Amount Paid For Broomsticks Transport Charges From office to Site', 'Site', 1000.0::numeric, 'Paid by DLR'),
  ('2026-05-12'::date, '', 'fuel', 'Being Amount Paid For Innova Diesel Expences', 'Innova', 4769.0::numeric, 'Paid by DSR'),
  ('2026-05-13'::date, '', 'fuel', 'Being Amount Paid For Activa Petrol Expences', 'Activa', 431.0::numeric, 'Paid by DLR'),
  ('2026-05-14'::date, 'HO', 'other', 'Being Amount Paid For GST Office Staff Food Expences', NULL, 5000.0::numeric, 'Paid by DLR'),
  ('2026-05-15'::date, '', 'other', 'Being Amount paid For Purchase a Domestic gas For Site Emp Usage 5 Nos * 2500', 'Site', 12500.0::numeric, 'Paid by DNR'),
  ('2026-05-15'::date, '', 'fuel', 'Being Amount Paid For Innova Diesel Expences', 'Innova', 3000.0::numeric, 'Paid by DLR'),
  ('2026-05-15'::date, 'HO', 'other', 'Being Amount Paid For Office Maid Charges For the Month Of May 26', NULL, 2500.0::numeric, 'Paid by DLR'),
  ('2026-05-15'::date, 'HO', 'other', 'Being Amount Paid For Office Apartment Monthly Mainteance Charges For thge Month of May 26', NULL, 3500.0::numeric, 'Paid by DLR'),
  ('2026-05-15'::date, '', 'transport', 'Being Amount Paid For Innova Tollgate Charges For The Month Of May 26', 'Innova', 3600.0::numeric, 'Paid by DLR'),
  ('2026-05-16'::date, '', 'fuel', 'Being Amount Paid For Activa Petrol Expences', 'Activa', 527.0::numeric, 'Paid by DLR'),
  ('2026-05-20'::date, '', 'fuel', 'Being Amount Paid For Innova Diesel Expences', 'Innova', 4078.0::numeric, 'Paid by DNR'),
  ('2026-05-20'::date, 'HO', 'other', 'Being Amount Paid For Office Gmail Storage Monthly Charges', NULL, 108.0::numeric, 'Paid by DLR'),
  ('2026-05-22'::date, '', 'other', 'Being Amount Paid For Site Documentation Charges', 'Site', 7500.0::numeric, 'Paid by DLR'),
  ('2026-05-22'::date, 'HO', 'other', 'Being Amount Paid For Purchase a Electrical Board With Wire 10 mtrs For office Usage', NULL, 1100.0::numeric, 'Paid by DLR'),
  ('2026-05-23'::date, '', 'fuel', 'Being Amount Paid For Activa Petrol Expences', 'Activa', 531.0::numeric, 'Paid by DLR'),
  ('2026-05-23'::date, '', 'fuel', 'Being Amount Paid For Innova Diesel Expences', 'Innova', 4689.0::numeric, 'Paid by DLR'),
  ('2026-05-25'::date, '', 'other', 'Being Amount Paid For Bpet1 CC Camera Recharge For one Month', 'Site', 301.0::numeric, 'Paid by DLR'),
  ('2026-05-27'::date, 'HO', 'other', 'Being Amount Paid For New Persons Requirement Through online', NULL, 826.0::numeric, 'Paid by DLR'),
  ('2026-05-30'::date, '', 'fuel', 'Being Amount Paid For Innova Diesel Expences', 'Innova', 4994.0::numeric, 'Paid by DNR'),
  ('2026-05-30'::date, 'HO', 'other', 'Being Amount Paid For Drinking Water Charges                  11 Cans * 35/-', NULL, 385.0::numeric, 'Paid by DLR'),
  ('2026-05-30'::date, '', 'other', 'Being Amount Paid For Purchase a Water Pipe 1 " For Site Usage', 'Site', 1710.0::numeric, 'Paid by DLR'),
  ('2026-05-30'::date, '', 'other', 'Being Amount Paid For Potlapally & Bpet2 Cooling Freezers Repair Charges', 'Site', 5000.0::numeric, 'Paid by DNR'),
  ('2026-05-30'::date, '', 'fuel', 'Being Amount Paid For Creta Petrol Expences', 'Creta', 4606.0::numeric, 'Paid by DLR'),
  ('2026-05-30'::date, 'HO', 'transport', 'Being Amount Paid For DSR Flight Ticket Charges From Hyd To Kolkata', NULL, 8875.0::numeric, 'Paid by DLR'),
  ('2026-06-01'::date, '', 'transport', 'Being Amount Paid For Dosth Ashokleyland Tollgate Recharge', 'Dosth-AshokLeyland', 500.0::numeric, 'Paid by DLR'),
  ('2026-06-02'::date, '', 'fuel', 'Being Amount Paid For Innova Diesel Expences', 'Innova', 5101.0::numeric, 'Paid by DLR'),
  ('2026-06-02'::date, '', 'fuel', 'Being Amount Paid For Activa Petrol Expences', 'Activa', 524.0::numeric, 'Paid by DLR'),
  ('2026-06-05'::date, '', 'transport', 'Being Amount Paid For Documents Send To Alwal For Solar Documentation', 'Site', 181.0::numeric, 'Paid by DLR'),
  ('2026-06-05'::date, 'HO', 'other', 'Being Amount Paid For Office Electricity Charges For the Month Of May 26', NULL, 1942.0::numeric, 'Paid by DLR'),
  ('2026-06-05'::date, 'HO', 'transport', 'Being Amount Paid For DSR Flight Ticket Charges From Kolkata To Hyderabad', NULL, 19765.0::numeric, 'Paid by DLR'),
  ('2026-06-05'::date, 'HO', 'other', 'Being Amount Paid For Office Microsoft One Drive Monthly Charges', NULL, 619.0::numeric, 'Paid by DLR'),
  ('2026-06-07'::date, '', 'fuel', 'Being Amount Paid For Innova Diesel Expences', 'Innova', 5101.0::numeric, 'Paid by DNR'),
  ('2026-06-09'::date, 'HO', 'other', 'Being Amount Paid For Purchase a Cleaning Items For Office Usage', NULL, 460.0::numeric, 'Paid by DLR'),
  ('2026-06-09'::date, '', 'fuel', 'Being Amount Paid For Activa Petrol Expences', 'Activa', 511.0::numeric, 'Paid by DLR'),
  ('2026-06-10'::date, '', 'fuel', 'Being Amount Paid For Innova Diesel Expences', 'Innova', 4685.0::numeric, 'Paid by DSR'),
  ('2026-06-11'::date, '', 'other', 'Being Amount Paid For Purchase a Soldering Wire & Paste For Site Usage', 'Site', 315.0::numeric, 'Paid by DLR'),
  ('2026-06-11'::date, '', 'other', 'Being Amount Paid For Purchase a Electrical Tapes For Site Usage', 'Site', 750.0::numeric, 'Paid by DLR'),
  ('2026-06-11'::date, 'HO', 'other', 'Being Amount Paid For Purchase a UPS For Office Usage', NULL, 3300.0::numeric, 'Paid by DLR'),
  ('2026-06-12'::date, '', 'other', 'Being Amount Paid For Purchase a Spiral Pocket Books For Site USage', 'Site', 60.0::numeric, 'Paid by DLR'),
  ('2026-06-15'::date, 'HO', 'other', 'Being Amount Paid For Office Maid Charges For the Month Of June 26', NULL, 2500.0::numeric, 'Paid by DLR'),
  ('2026-06-15'::date, 'HO', 'other', 'Being Amount Paid For Office Apartment Monthly Mainteance Charges For thge Month of june 26', NULL, 3500.0::numeric, 'Paid by DLR'),
  ('2026-06-15'::date, '', 'transport', 'Being Amount Paid For Innova Tollgate Charges For The Month Of June 26', 'Innova', 3600.0::numeric, 'Paid by DLR'),
  ('2026-06-17'::date, '', 'other', 'Being Amount Paid For DR Op Singh Hotel Bill', 'Site', 6142.0::numeric, 'Paid by DLR'),
  ('2026-06-18'::date, '', 'maintenance', 'Being Amount Paid For Activa Insurance Renewal Charges', 'Activa', 3495.0::numeric, 'Paid by DLR'),
  ('2026-06-20'::date, '', 'fuel', 'Being Amount Paid For Activa Petrol Expences', 'Activa', 544.0::numeric, 'Paid by DLR'),
  ('2026-06-20'::date, 'HO', 'other', 'Being Amount Paid For Office Printer Catridges Refilling Charges', NULL, 400.0::numeric, 'Paid by DLR'),
  ('2026-06-20'::date, 'HO', 'transport', 'Being Amount Paid For Rapido Charges From Sri Sai Poultry To Head Office', NULL, 294.0::numeric, 'Paid by DLR'),
  ('2026-06-20'::date, 'HO', 'other', 'Being Amount Paid For Office Gmail Storage Monthly Charges', NULL, 108.0::numeric, 'Paid by DLR'),
  ('2026-06-21'::date, '', 'fuel', 'Being Amount Paid For Innova Diesel Expences', 'Innova', 4852.0::numeric, 'Paid by DLR'),
  ('2026-06-22'::date, '', 'other', 'Being Amount Paid For Purchase a Taparia Tool Kit For Site Usage', 'Site', 2104.0::numeric, 'Paid by DLR'),
  ('2026-06-22'::date, '', 'other', 'Being Amount Paid For Purchase a MK1 13-22A Relays For Site USage', 'Site', 6737.0::numeric, 'Paid by DLR'),
  ('2026-06-22'::date, 'HO', 'other', 'Being Amount Paid For Office Mobile recharge', NULL, 619.0::numeric, 'Paid by DLR'),
  ('2026-06-23'::date, '', 'other', 'Being Amount Paid For Purchase a Denplast For Transformer Cleaning in Site', 'Site', 885.0::numeric, 'Paid by DLR'),
  ('2026-06-23'::date, '', 'transport', 'Being Amount Paid For Porter Charges From Hyderabad To Site For Send a Inlet Valves , Ball Valves & Motors', 'Site', 1000.0::numeric, 'Paid by DLR'),
  ('2026-06-27'::date, '', 'fuel', 'Being Amount Paid For Innova Petrol Expences', 'Innova', 4548.0::numeric, 'Paid by DNR'),
  ('2026-06-27'::date, '', 'fuel', 'Being Amount Paid For Innova Diesel Expences', 'Innova', 5091.0::numeric, 'Paid by DLR'),
  ('2026-06-30'::date, 'HO', 'other', 'Being Amount Paid For Drinking Water Charges                  10 Cans * 35/-', NULL, 350.0::numeric, 'Paid by DLR'),
  ('2026-07-01'::date, '', 'fuel', 'Being Amount Paid For Activa Petrol Expences', 'Activa', 561.0::numeric, 'Paid by DLR'),
  ('2026-07-02'::date, 'HO', 'transport', 'Being Amount Paid For Travelling Expences To Office Attender Venktaiah From Office To Balanagar to & Pro For Medicine Given to  Site', NULL, 295.0::numeric, 'Paid by DLR'),
  ('2026-07-03'::date, '', 'fuel', 'Being Amount Paid For Innova Petrol Expences', 'Innova', 4539.0::numeric, 'Paid by DNR'),
  ('2026-07-04'::date, '', 'maintenance', 'Being Amount Paid For Activa Service Charges', 'Activa', 1200.0::numeric, 'Paid by DLR'),
  ('2026-07-05'::date, 'HO', 'other', 'Being Amount Paid For Office Electricity Charges For the Month Of June 26', NULL, 1547.0::numeric, 'Paid by DLR'),
  ('2026-07-05'::date, 'HO', 'other', 'Being Amount Paid For Office Microsoft One Drive Monthly Charges', NULL, 619.0::numeric, 'Paid by DLR'),
  ('2026-07-06'::date, '', 'fuel', 'Being Amount Paid For Innova Petrol Expences', 'Innova', 5061.0::numeric, 'Paid by DNR'),
  ('2026-07-07'::date, '', 'fuel', 'Being Amount Paid For Activa Petrol Expences', 'Activa', 550.0::numeric, 'Paid by DLR'),
  ('2026-07-07'::date, '', 'fuel', 'Being Amount Paid For Innova Petrol Expences', 'Innova', 9130.0::numeric, 'Paid by DNR'),
  ('2026-07-08'::date, 'HO', 'other', 'Being Amount Paid For Office Airtel Internet Charges', NULL, 1500.0::numeric, 'Paid by DLR'),
  ('2026-07-09'::date, 'HO', 'other', 'Being Amount Paid For Office Electrical Work Charges', NULL, 2000.0::numeric, 'Paid by DLR'),
  ('2026-07-09'::date, '', 'transport', 'Being Amount Paid For Dosth Ashokleyland Tollgate Recharge', 'Dosth-AshokLeyland', 500.0::numeric, 'Paid by DLR'),
  ('2026-07-10'::date, '', 'other', 'Being Amount Paid For Site CC Camera Recharges For Two Months 09 Nos ,01 Camera One Month', 'Site', 5890.0::numeric, 'Paid by DLR'),
  ('2026-07-10'::date, '', 'maintenance', 'Being Amount Paid For Dosth Ashokleyland Road Tax Charges', 'Dosth-AshokLeyland', 1178.0::numeric, 'Paid by DLR'),
  ('2026-07-13'::date, '', 'fuel', 'Being Amount Paid For Innova Petrol Expences', 'Innova', 4800.0::numeric, 'Paid by DLR'),
  ('2026-07-13'::date, 'HO', 'other', 'Being Amount Paid For DSR Airtel Yearly Recharge ', NULL, 3601.0::numeric, 'Paid by DLR'),
  ('2026-07-14'::date, '', 'fuel', 'Being Amount Paid For Activa Petrol Expences', 'Activa', 551.0::numeric, 'Paid by DLR'),
  ('2026-07-14'::date, 'HO', 'other', 'Being Amount Paid For Purchase a Plumbing Items For Office Usage', NULL, 1655.0::numeric, 'Paid by DLR'),
  ('2026-07-14'::date, 'HO', 'other', 'Being Amount Paid For Purchase a Godrej Lock For Office Usage', NULL, 1800.0::numeric, 'Paid by DLR'),
  ('2026-07-14'::date, 'HO', 'other', 'Being Amount Paid For Purchase a Electrical Items For Office Usage', NULL, 1320.0::numeric, 'Paid by DLR'),
  ('2026-07-14'::date, 'HO', 'other', 'Being Amount Paid For Purchase a Electrical Box For Office Usage', NULL, 850.0::numeric, 'Paid by DLR'),
  ('2026-07-14'::date, 'HO', 'other', 'Being Amount Paid For Purchase a Electrical Items For Office Usage', NULL, 2185.0::numeric, 'Paid by DLR'),
  ('2026-07-15'::date, '', 'other', 'Being Amount Paid For Purchase a Dabur Gut Health 08 Ltrs For Site Usage ', 'Site', 3776.0::numeric, 'Paid by DLR'),
  ('2026-07-15'::date, '', 'other', 'Being Amount Paid For Purchase a Dabur Gut Health 09 Ltrs For Site Usage ', 'Site', 4248.0::numeric, 'Paid by DLR'),
  ('2026-07-15'::date, '', 'other', 'Being Amount Paid For Solar Documentation in Site Near Electrical Office Expences', 'Site', 3500.0::numeric, 'Paid by DLR'),
  ('2026-07-15'::date, '', 'fuel', 'Being Amount Paid For Innova Petrol Expences', 'Innova', 4000.0::numeric, 'Paid by DLR'),
  ('2026-07-15'::date, 'HO', 'other', 'Being Amount Paid For Office Maid Charges For the Month Of July 26', NULL, 2500.0::numeric, 'Paid by DLR'),
  ('2026-07-15'::date, 'HO', 'other', 'Being Amount Paid For Office Apartment Monthly Mainteance Charges For thge Month of July 26', NULL, 3500.0::numeric, 'Paid by DLR'),
  ('2026-07-15'::date, '', 'transport', 'Being Amount Paid For Innova Tollgate Charges For The Month Of July 26', 'Innova', 3600.0::numeric, 'Paid by DLR'),
  ('2026-07-16'::date, 'HO', 'other', 'Being Amount Paid For Purchase a Puja Items For office Usage', NULL, 1097.0::numeric, 'Paid by DLR'),
  ('2026-07-16'::date, 'HO', 'other', 'Being Amount Paid For Purchase a Gumadikayalu For Office usage', NULL, 430.0::numeric, 'Paid by DLR'),
  ('2026-07-16'::date, 'HO', 'other', 'Being Amount Paid For Purchase a Pulu For Office usage', NULL, 120.0::numeric, 'Paid by DLR'),
  ('2026-07-16'::date, 'HO', 'other', 'Being Amount Paid For Purchase a Five Types Of Fruits For Office usage', NULL, 930.0::numeric, 'Paid by DLR'),
  ('2026-07-16'::date, '', 'transport', 'Being Amount Paid For Innova Tollgate Charges For The Month Of July 26', 'Innova', 3600.0::numeric, 'Paid by DLR'),
  ('2026-07-16'::date, '', 'fuel', 'Being Amount Paid For Innova Diesel Expences', 'Innova', 5199.0::numeric, 'Paid by DNR'),
  ('2026-07-16'::date, 'HO', 'other', 'Being Amount Paid For Purchase a Sweet Box 02 Nos For Office usage', NULL, 1120.0::numeric, 'Paid by DLR'),
  ('2026-07-17'::date, '', 'fuel', 'Being Amount Paid For Creta Petrol Expences', 'Creta', 4815.0::numeric, 'Paid by DLR'),
  ('2026-07-18'::date, '', 'other', 'Being Amount Paid For Purchase a HT Meter Box Nos For Site Usage', 'Site', 5428.0::numeric, 'Paid by DLR'),
  ('2026-07-18'::date, '', 'other', 'Being Amount Paid For Purchase a HT Meter Box Nos For Site Usage', 'Site', 5428.0::numeric, 'Paid by DLR'),
  ('2026-07-20'::date, 'HO', 'other', 'Being Amount Paid For Purchase a Highspeed Fan For Office usage', NULL, 3200.0::numeric, 'Paid by DLR'),
  ('2026-07-20'::date, 'HO', 'other', 'Being Amount Paid For Office Gmail Storage Monthly Charges', NULL, 108.0::numeric, 'Paid by DLR'),
  ('2026-07-20'::date, '', 'fuel', 'Being Amount Paid For Activa Petrol Expences', 'Activa', 504.0::numeric, 'Paid by DLR'),
  ('2026-07-20'::date, '', 'other', 'Being Amount Paid For Purchase a 6205 Bearings For Site Usage', 'Site', 1188.0::numeric, 'Paid by DLR'),
  ('2026-07-20'::date, '', 'other', 'Being Amount Paid For Purchase a Welding Rods For Site Usage', 'Site', 600.0::numeric, 'Paid by DLR'),
  ('2026-07-22'::date, '', 'other', 'Being Amount Paid For Purchase a Grease 10 Kgs For Site Usage', 'Site', 1700.0::numeric, 'Paid by DLR'),
  ('2026-07-23'::date, 'HO', 'other', 'Being Amount Paid For Tea & Tiffin Expences For Office Staff While Visting Site', NULL, 215.0::numeric, 'Paid by DLR'),
  ('2026-07-23'::date, '', 'fuel', 'Being Amount Paid For Innova Diesel Expences', 'Innova', 4720.0::numeric, 'Paid by DNR'),
  ('2026-07-23'::date, '', 'transport', 'Being Amount Paid For Porter Charges From Hyderabad To Site For Send Surya Cem Bags', 'Site', 3300.0::numeric, 'Paid by DLR'),
  ('2026-07-24'::date, '', 'fuel', 'Being Amount Paid For Activa Petrol Expences', 'Activa', 500.0::numeric, 'Paid by DLR'),
  ('2026-07-25'::date, 'HO', 'other', 'Being Amount Paid For DTDC Charges For Send a Current Account Documents To kolkata', NULL, 550.0::numeric, 'Paid by DLR'),
  ('2026-07-28'::date, '', 'fuel', 'Being Amount Paid For Innova Petrol Expences', 'Innova', 4842.0::numeric, 'Paid by DSR'),
  ('2026-07-28'::date, '', 'other', 'Being Amount Paid For Bolero Self Motor & DG Alternator repair Charges', 'Site', 7600.0::numeric, 'Paid by DNR'),
  ('2026-07-31'::date, '', 'fuel', 'Being Amount Paid For Activa Petrol Expences', 'Activa', 521.0::numeric, 'Paid by DLR'),
  ('2026-07-31'::date, 'HO', 'other', 'Being Amount Paid For Office Tea & Curd Expences', NULL, 1065.0::numeric, 'Paid by DLR')
),
ins AS (
  INSERT INTO public.farm_expenses (expense_date, farm_id, category, description, vendor, amount, remarks)
  SELECT v.expense_date, f.id, v.category, v.description, NULLIF(v.vendor,''), v.amount, v.remarks
  FROM v LEFT JOIN public.farms f ON f.code = NULLIF(v.farm_code,'')
  RETURNING id, expense_date, farm_id, category, description, vendor, amount, remarks
)
INSERT INTO public.cash_book (txn_date, txn_type, category, farm_id, description, party_name, amount_in, amount_out, payment_mode, remarks, farm_expense_id)
SELECT ins.expense_date, 'payment', 'expense',
  COALESCE(ins.farm_id, CASE WHEN ins.vendor IS NOT NULL THEN (SELECT id FROM public.farms WHERE code='HO') END),
  ins.category || COALESCE(' — '||ins.vendor, '') || ' — ' || ins.description,
  ins.vendor, 0, ins.amount, 'cash', ins.remarks, ins.id
FROM ins;

SELECT 'farm_expenses' AS tbl, count(*)::int AS n FROM public.farm_expenses WHERE created_at > now() - interval '2 minutes'
UNION ALL
SELECT 'cash_book', count(*)::int FROM public.cash_book WHERE created_at > now() - interval '2 minutes';
