-- Migration 1119: load the shed line master for the two sheets that reconcile.
--
-- LOADED HERE:
--   Kethireddypally  -- 12 sheds, BOXES per line (image 1). Every shed's line
--     values sum to the total printed on the sheet, and the 12 shed totals sum
--     to 24,044 which is exactly what sheds.total_boxes already holds, shed by
--     shed. Independently confirmed, not merely internally consistent.
--   Agraharam Potlapally -- 4 sheds, CAPACITY BIRDS per line (image 2). All 28
--     printed column totals reconcile against the line values.
--
-- DELIBERATELY NOT LOADED:
--   Bodjanampet - 1  -- transcription is not trustworthy. Shed 2 side A reads
--     1,443 against a printed 1,442, and Shed 1 prints no totals at all with no
--     male counts. Waiting on a clearer source.
--   Bodjanampet - 2 (VHL) -- owner reported a mistake in the sheet. Held at the
--     owner's instruction even though its totals do reconcile.
--
-- Everything is additive: shed_lines was empty, no screen reads it, and no shed
-- is line-managed. Nothing that anybody is using today changes.
--
-- is_provisional is TRUE on every row, so these read as figures to be confirmed
-- rather than as measurements. Correcting any number later is a plain update.
--
-- CONVENTIONS, all forced by the sheets themselves:
--  * Kethireddypally growing sheds 1-4 print a single "Cage" column with no A/B
--    split, matching the shed master which holds a total only for those four.
--    Their lines are recorded on side A, noted in remarks.
--  * Agraharam sheds 1-2 are FOUR-sided (A-D); sheds 3-4 are two-sided. Side
--    count is per shed, not fixed.
--  * On Agraharam sheds 1-2, lines 6/7/10/11 of sides B and C are male-only, so
--    capacity_female is 0 there. On sheds 3-4 the same lines carry both sexes.
--  * Kethireddypally rows carry boxes with capacity NULL; Agraharam rows carry
--    capacity with boxes NULL. The sheets measure different things and neither
--    is inferred from the other.

INSERT INTO public.shed_lines
  (shed_id, side, line_no, boxes, capacity_female, capacity_male, is_provisional, remarks)
SELECT s.id, v.side, v.line_no, v.boxes, v.cap_f, v.cap_m, TRUE, v.remarks
FROM (VALUES
  ('Kethireddypally','10','A',1,54,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','A',2,54,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','A',3,54,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','A',4,54,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','A',5,54,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','A',6,54,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','A',7,54,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','A',8,54,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','A',9,54,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','A',10,54,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','A',11,54,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','A',12,54,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','A',13,54,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','A',14,54,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','A',15,54,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','A',16,54,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','B',1,58,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','B',2,58,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','B',3,58,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','B',4,58,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','B',5,58,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','B',6,58,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','B',7,58,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','B',8,58,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','B',9,58,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','B',10,58,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','B',11,58,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','B',12,58,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','B',13,58,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','B',14,58,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','B',15,58,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','10','B',16,58,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','11','A',1,40,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','11','A',2,40,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','11','A',3,40,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','11','A',4,40,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','11','A',5,40,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','11','A',6,40,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','11','A',7,40,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','11','A',8,40,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','11','A',9,40,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','11','A',10,40,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','11','A',11,40,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','11','A',12,40,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','11','B',1,70,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','11','B',2,70,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','11','B',3,70,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','11','B',4,70,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','11','B',5,70,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','11','B',6,70,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','11','B',7,70,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','11','B',8,70,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','11','B',9,70,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','11','B',10,70,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','11','B',11,70,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','11','B',12,70,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','12','A',1,40,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','12','A',2,40,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','12','A',3,40,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','12','A',4,40,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','12','A',5,40,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','12','A',6,40,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','12','A',7,40,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','12','A',8,40,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','12','A',9,40,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','12','A',10,40,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','12','A',11,40,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','12','A',12,40,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','12','B',1,70,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','12','B',2,70,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','12','B',3,70,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','12','B',4,70,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','12','B',5,70,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','12','B',6,70,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','12','B',7,70,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','12','B',8,70,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','12','B',9,70,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','12','B',10,70,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','12','B',11,70,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','12','B',12,70,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','A',1,55,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','A',2,55,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','A',3,55,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','A',4,55,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','A',5,55,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','A',6,55,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','A',7,55,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','A',8,55,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','A',9,55,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','A',10,55,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','A',11,55,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','A',12,55,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','A',13,55,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','A',14,55,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','B',1,37,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','B',2,37,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','B',3,37,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','B',4,37,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','B',5,37,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','B',6,37,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','B',7,37,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','B',8,37,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','B',9,37,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','B',10,37,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','B',11,37,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','B',12,37,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','B',13,37,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','6','B',14,37,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','5','A',1,44,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','5','A',2,44,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','5','A',3,44,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','5','A',4,44,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','5','A',5,44,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','5','A',6,44,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','5','A',7,44,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','5','A',8,44,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','5','A',9,44,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','5','A',10,44,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','5','A',11,44,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','5','A',12,44,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','5','B',1,47,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','5','B',2,47,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','5','B',3,47,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','5','B',4,47,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','5','B',5,47,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','5','B',6,47,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','5','B',7,47,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','5','B',8,47,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','5','B',9,47,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','5','B',10,47,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','5','B',11,47,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','5','B',12,47,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','1','A',1,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','1','A',2,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','1','A',3,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','1','A',4,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','1','A',5,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','1','A',6,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','1','A',7,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','1','A',8,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','1','A',9,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','1','A',10,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','1','A',11,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','1','A',12,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','1','A',13,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','1','A',14,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','1','A',15,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','1','A',16,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','2','A',1,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','2','A',2,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','2','A',3,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','2','A',4,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','2','A',5,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','2','A',6,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','2','A',7,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','2','A',8,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','2','A',9,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','2','A',10,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','2','A',11,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','2','A',12,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','2','A',13,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','2','A',14,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','2','A',15,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','2','A',16,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','3','A',1,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','3','A',2,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','3','A',3,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','3','A',4,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','3','A',5,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','3','A',6,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','3','A',7,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','3','A',8,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','3','A',9,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','3','A',10,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','3','A',11,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','3','A',12,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','3','A',13,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','3','A',14,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','3','A',15,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','3','A',16,144,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','4','A',1,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','4','A',2,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','4','A',3,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','4','A',4,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','4','A',5,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','4','A',6,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','4','A',7,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','4','A',8,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','4','A',9,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','4','A',10,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','4','A',11,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','4','A',12,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','4','A',13,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','4','A',14,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','4','A',15,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','4','A',16,143,NULL,NULL,'Kethireddypally line sheet (boxes); shed has no A/B split, all lines recorded on side A'),
  ('Kethireddypally','7','A',1,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','A',2,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','A',3,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','A',4,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','A',5,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','A',6,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','A',7,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','A',8,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','A',9,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','A',10,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','A',11,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','A',12,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','A',13,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','A',14,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','A',15,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','A',16,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','B',1,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','B',2,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','B',3,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','B',4,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','B',5,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','B',6,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','B',7,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','B',8,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','B',9,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','B',10,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','B',11,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','B',12,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','B',13,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','B',14,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','B',15,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','7','B',16,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','A',1,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','A',2,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','A',3,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','A',4,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','A',5,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','A',6,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','A',7,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','A',8,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','A',9,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','A',10,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','A',11,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','A',12,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','A',13,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','A',14,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','A',15,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','A',16,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','B',1,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','B',2,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','B',3,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','B',4,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','B',5,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','B',6,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','B',7,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','B',8,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','B',9,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','B',10,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','B',11,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','B',12,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','B',13,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','B',14,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','B',15,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','8','B',16,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','A',1,83,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','A',2,83,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','A',3,83,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','A',4,83,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','A',5,83,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','A',6,83,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','A',7,83,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','A',8,83,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','A',9,83,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','A',10,83,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','A',11,83,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','A',12,83,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','A',13,83,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','A',14,83,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','A',15,83,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','A',16,83,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','B',1,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','B',2,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','B',3,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','B',4,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','B',5,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','B',6,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','B',7,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','B',8,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','B',9,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','B',10,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','B',11,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','B',12,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','B',13,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','B',14,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','B',15,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Kethireddypally','9','B',16,84,NULL,NULL,'Kethireddypally line sheet (boxes)'),
  ('Agraharam Potlapally','1','A',1,NULL,98,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','A',2,NULL,98,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','A',3,NULL,98,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','A',4,NULL,98,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','A',5,NULL,100,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','A',6,NULL,97,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','A',7,NULL,98,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','A',8,NULL,101,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','A',9,NULL,101,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','A',10,NULL,100,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','A',11,NULL,100,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','A',12,NULL,98,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','A',13,NULL,98,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','A',14,NULL,98,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','A',15,NULL,98,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','A',16,NULL,98,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','B',1,NULL,91,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','B',2,NULL,91,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','B',3,NULL,91,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','B',4,NULL,91,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','B',5,NULL,91,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','B',6,NULL,0,78,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','B',7,NULL,0,78,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','B',8,NULL,91,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','B',9,NULL,91,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','B',10,NULL,0,78,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','B',11,NULL,0,78,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','B',12,NULL,91,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','B',13,NULL,91,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','B',14,NULL,91,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','B',15,NULL,91,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','B',16,NULL,91,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','C',1,NULL,92,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','C',2,NULL,92,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','C',3,NULL,92,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','C',4,NULL,92,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','C',5,NULL,95,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','C',6,NULL,0,79,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','C',7,NULL,0,79,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','C',8,NULL,95,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','C',9,NULL,95,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','C',10,NULL,0,79,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','C',11,NULL,0,79,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','C',12,NULL,95,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','C',13,NULL,92,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','C',14,NULL,92,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','C',15,NULL,92,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','C',16,NULL,92,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','D',1,NULL,109,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','D',2,NULL,109,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','D',3,NULL,109,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','D',4,NULL,110,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','D',5,NULL,109,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','D',6,NULL,112,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','D',7,NULL,111,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','D',8,NULL,111,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','D',9,NULL,111,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','D',10,NULL,112,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','D',11,NULL,112,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','D',12,NULL,110,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','D',13,NULL,110,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','D',14,NULL,110,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','D',15,NULL,109,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','1','D',16,NULL,109,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','A',1,NULL,97,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','A',2,NULL,97,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','A',3,NULL,97,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','A',4,NULL,97,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','A',5,NULL,97,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','A',6,NULL,97,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','A',7,NULL,97,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','A',8,NULL,97,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','A',9,NULL,97,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','A',10,NULL,97,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','A',11,NULL,97,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','A',12,NULL,97,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','A',13,NULL,97,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','A',14,NULL,97,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','A',15,NULL,97,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','A',16,NULL,97,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','B',1,NULL,92,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','B',2,NULL,92,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','B',3,NULL,92,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','B',4,NULL,92,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','B',5,NULL,92,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','B',6,NULL,0,79,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','B',7,NULL,0,79,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','B',8,NULL,92,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','B',9,NULL,92,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','B',10,NULL,0,79,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','B',11,NULL,0,79,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','B',12,NULL,92,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','B',13,NULL,92,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','B',14,NULL,92,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','B',15,NULL,92,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','B',16,NULL,92,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','C',1,NULL,102,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','C',2,NULL,102,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','C',3,NULL,102,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','C',4,NULL,102,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','C',5,NULL,102,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','C',6,NULL,0,87,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','C',7,NULL,0,87,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','C',8,NULL,102,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','C',9,NULL,102,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','C',10,NULL,0,87,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','C',11,NULL,0,87,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','C',12,NULL,102,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','C',13,NULL,102,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','C',14,NULL,102,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','C',15,NULL,102,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','C',16,NULL,102,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','D',1,NULL,100,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','D',2,NULL,100,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','D',3,NULL,100,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','D',4,NULL,100,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','D',5,NULL,100,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','D',6,NULL,100,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','D',7,NULL,100,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','D',8,NULL,100,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','D',9,NULL,100,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','D',10,NULL,100,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','D',11,NULL,100,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','D',12,NULL,100,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','D',13,NULL,100,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','D',14,NULL,100,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','D',15,NULL,100,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','2','D',16,NULL,100,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','A',1,NULL,192,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','A',2,NULL,192,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','A',3,NULL,192,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','A',4,NULL,192,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','A',5,NULL,192,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','A',6,NULL,98,80,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','A',7,NULL,98,80,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','A',8,NULL,192,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','A',9,NULL,192,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','A',10,NULL,98,80,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','A',11,NULL,98,80,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','A',12,NULL,192,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','A',13,NULL,192,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','A',14,NULL,192,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','A',15,NULL,192,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','A',16,NULL,192,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','B',1,NULL,204,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','B',2,NULL,204,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','B',3,NULL,204,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','B',4,NULL,204,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','B',5,NULL,204,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','B',6,NULL,100,88,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','B',7,NULL,100,88,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','B',8,NULL,204,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','B',9,NULL,204,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','B',10,NULL,100,88,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','B',11,NULL,100,88,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','B',12,NULL,204,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','B',13,NULL,204,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','B',14,NULL,204,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','B',15,NULL,204,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','3','B',16,NULL,204,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','A',1,NULL,204,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','A',2,NULL,204,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','A',3,NULL,204,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','A',4,NULL,204,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','A',5,NULL,204,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','A',6,NULL,100,88,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','A',7,NULL,100,88,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','A',8,NULL,204,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','A',9,NULL,204,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','A',10,NULL,100,88,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','A',11,NULL,100,88,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','A',12,NULL,204,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','A',13,NULL,204,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','A',14,NULL,204,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','A',15,NULL,204,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','A',16,NULL,204,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','B',1,NULL,192,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','B',2,NULL,192,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','B',3,NULL,192,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','B',4,NULL,192,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','B',5,NULL,192,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','B',6,NULL,98,80,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','B',7,NULL,98,80,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','B',8,NULL,192,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','B',9,NULL,192,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','B',10,NULL,98,80,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','B',11,NULL,98,80,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','B',12,NULL,192,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','B',13,NULL,192,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','B',14,NULL,192,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','B',15,NULL,192,0,'Agraharam Potlapally line sheet (capacity birds)'),
  ('Agraharam Potlapally','4','B',16,NULL,192,0,'Agraharam Potlapally line sheet (capacity birds)')
) AS v(farm, shed_no, side, line_no, boxes, cap_f, cap_m, remarks)
JOIN public.farms fm ON fm.name = v.farm
JOIN public.sheds s  ON s.farm_id = fm.id AND s.shed_no = v.shed_no
WHERE NOT EXISTS (
  SELECT 1 FROM public.shed_lines sl
  WHERE sl.shed_id = s.id AND sl.side = v.side AND sl.line_no = v.line_no
);

-- VERIFY 1: rows landed, per farm.
SELECT string_agg(x.line, ' | ' ORDER BY x.line) AS lines_by_farm
FROM (
  SELECT fm.name || '=' || count(*)::text AS line
  FROM public.shed_lines sl
  JOIN public.sheds s ON s.id = sl.shed_id
  JOIN public.farms fm ON fm.id = s.farm_id
  GROUP BY fm.name
) x;

-- VERIFY 2: Kethireddypally line boxes must total 24,044 and must agree with
-- sheds.total_boxes for every one of the 12 sheds. Zero mismatches expected.
SELECT COALESCE(sum(sl.boxes),0)::int AS kpally_line_boxes,
       (SELECT count(*) FROM (
          SELECT s.id
          FROM public.shed_lines sl2
          JOIN public.sheds s ON s.id = sl2.shed_id
          JOIN public.farms fm2 ON fm2.id = s.farm_id AND fm2.name = 'Kethireddypally'
          GROUP BY s.id, s.total_boxes
          HAVING sum(sl2.boxes) <> s.total_boxes
       ) m)::int AS sheds_disagreeing_with_master
FROM public.shed_lines sl
JOIN public.sheds s ON s.id = sl.shed_id
JOIN public.farms fm ON fm.id = s.farm_id
WHERE fm.name = 'Kethireddypally';

-- VERIFY 3: Agraharam per shed and side, female and male.
SELECT string_agg(y.line, ' | ' ORDER BY y.line) AS agraharam_totals
FROM (
  SELECT s.shed_no || sl.side || '=' || sum(sl.capacity_female)::text
         || '/m' || sum(sl.capacity_male)::text AS line
  FROM public.shed_lines sl
  JOIN public.sheds s ON s.id = sl.shed_id
  JOIN public.farms fm ON fm.id = s.farm_id
  WHERE fm.name = 'Agraharam Potlapally'
  GROUP BY s.shed_no, sl.side
) y;

-- VERIFY 4: the two held farms must still have no lines at all.
SELECT COALESCE(sum(CASE WHEN fm.name LIKE 'Bodjanampet%' THEN 1 ELSE 0 END),0)::int AS held_farm_lines
FROM public.shed_lines sl
JOIN public.sheds s ON s.id = sl.shed_id
JOIN public.farms fm ON fm.id = s.farm_id;

-- VERIFY 5: nothing was switched on, and no daily data was created.
SELECT (SELECT count(*) FROM public.sheds WHERE line_managed)::int AS line_managed_sheds,
       (SELECT count(*) FROM public.line_production)::int          AS line_production_rows;
